/* GENERATED by tools/r5/sim_r5.py from tools/r7/present_oracle.py -- do not edit */
#define G3_PRESENT_WORDS 19
#define G3_PRESENT_RING 32
#define G3_IX_GMC 9
#define G3_IX_SRC_PO 11
#define G3_IX_DST_PO 12
#define G3_IX_SRC_XY 14
#define G3_IX_DST_XY 15
#define G3_IX_WH 16
static const unsigned long g3PresentWant[G3_PRESENT_WORDS] = {
    0x000005c8UL, 0x00060000UL, 0x000005baUL, 0x1fff1fffUL, 0x000005b3UL, 0xffffffffUL, 0x000005b0UL, 0x00000003UL, 0x0000051bUL, 0x52cc36f3UL, 0x0001050aUL, 0x0c800a78UL, 0x10000000UL, 0x00020564UL, 0x00000257UL, 0x00000000UL, 0x03200001UL, 0x000005c8UL, 0x00050000UL
};
