/* GENERATED by tools/r5/sim_r5.py from tools/r7/present_oracle.py -- do not edit */
static const unsigned long g3PresentWant[13] = {
    0x000005c8UL, 0x00060000UL, 0x0000051bUL, 0x52cc36f3UL, 0x0001050aUL, 0x0c800a78UL, 0x10000000UL, 0x00020564UL, 0x00000257UL, 0x00000000UL, 0x03200001UL, 0x000005c8UL, 0x00050000UL
};
