/*
 * rdnreplay.c - G4-8 (docs/G4_8_REPLAY_PLAN.md 2): resubmit a RECORDED client stream through the
 * character device, the way the Mesa library submits (SUBMIT2, copyin from the client's own
 * buffer), as many times as asked, with breadcrumbs on NFS before and after every submission.
 *
 * Pure C, as tools/r7/rdnr7dev.c: no -lDriver, no #import.  Build on the target:
 *   cc -O -Wall -o rdnreplay rdnreplay.c
 *
 * Usage:
 *   rdnreplay <runid> <major> <file> words=<N> reps=<R> [crumb=<path>] [stop=<k>] [async=1]
 *     runid   decimal, fresh per call; the seed is (runid mod 4000000) * 1000 + k + 1
 *     major   the driver's character major (38 on this card)
 *     file    little-endian 32-bit words the library once submitted (RDNMesaTraceLast)
 *     N       how many words of the file to send (1..4068); a prefix must end on a packet boundary
 *     R       repetitions, 1..999
 *     crumb   a file on NFS: "rep k seed" before each ioctl, "done k status why at drawn" after
 *     stop    stop after repetition k's crumb, BEFORE its ioctl (a self-test of the crumbs)
 *     async   G5-2 (docs/G5_2_ASYNC_SUBMIT_PLAN.md 6): SUBMIT3 instead of SUBMIT2 -- the kernel
 *             accepts and returns -- and one RETIRE after the last repetition, printed
 *
 * Gates before anything is sent (any failure: nothing submitted):
 *   CAPS   magic, version, ready, cpRunning, maxWords >= N  (the kernel's "nodev" preconditions
 *          show here as ready/cpRunning: OSRDNDisplay.m r7bSubmit2)
 *   walk   PACKET0/PACKET2/PACKET3 headers walked from word 0 end EXACTLY at N; every PACKET0
 *          register is in the allow list the oracle generates (tools/r7/verify_oracle.py --c-tables)
 *   win    the stream's RB3D_COLOROFFSET equals caps.winStart -- the words are NOT relocated;
 *          a stream from a boot with another window is refused here
 *
 * The CAPS fd is closed before the repetitions: the driver's open is a binary latch (rdnr7dev.c
 * gate C), so each repetition does open -> SUBMIT2 -> close like the library's un-held path.
 *
 * Exit codes:
 *   0  done (every repetition drawn, or stopped by stop=)   2  usage / file
 *   3  mknod/open failed        4  CAPS refused or a CAPS gate     7  walk or window gate
 *   6  SUBMIT2 could not be sent (ioctl rc != 0; the reply block is then NOT valid)
 *   8  the driver refused or did not draw (status, why, drawn printed)
 *
 * Every line starts "RDNREPLAY ".
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "../../OSRDNDisplay/OSRDNDisplay_reloc.tproj/osrdn_r7b.h"

extern int mknod(const char *, int, int);
extern int open(const char *, int, ...);
extern int ioctl(int, int, char *);
extern int close(int);
extern int write(int, const void *, unsigned int);
extern int fsync(int);

#define NODE            "/dev/rdnvram0"
#define NODE_RDWR       2                       /* O_RDWR, bsd/sys/fcntl.h 36 (OSRDNMesaTri.c NODE_RDWR) */
#define CRUMB_FLAGS     (1 | 01000 | 010)       /* O_WRONLY | O_CREAT | O_APPEND, bsd/sys/fcntl.h */
#define MAX_WORDS       4068UL                  /* OSRDN_R7B_MAX_WORDS */
#define MAX_REPS        999UL                   /* the seed formula leaves three digits for k */
#define RB3D_COLOROFFSET 0x1c40UL

/* GENERATED by tools/r7/verify_oracle.py --c-tables (the same 42 as the kernel's cpR7Allow);
   tools/g48/check_replay.py compares the two */
static const unsigned short allow[42] = {
    0x1c14, 0x1c20, 0x1c24, 0x1c28, 0x1c2c, 0x1c38, 0x1c3c, 0x1c40,
    0x1c44, 0x1c48, 0x1c4c, 0x1c50, 0x1cd8, 0x1cdc, 0x1ce0, 0x1ce4,
    0x1ce8, 0x1cec, 0x1d60, 0x1d7c, 0x1d84, 0x2080, 0x2088, 0x208c,
    0x20b0, 0x2140, 0x2180, 0x2284, 0x26c0, 0x26f0, 0x2c00, 0x2c04,
    0x2c08, 0x2c0c, 0x2c10, 0x2c1c, 0x2cc4, 0x2d00, 0x2f00, 0x2f04,
    0x2f08, 0x2f0c
};

static int crumbFd = -1;

static void
crumb(const char *what, unsigned long a, unsigned long b, unsigned long c, unsigned long d, unsigned long e)
{
    char line[160];

    if (crumbFd < 0)
        return;
    if (c == ~0UL)
        sprintf(line, "%s %lu %lu\n", what, a, b);
    else
        sprintf(line, "%s %lu %lu %lu %lu %lu\n", what, a, b, c, d, e);
    (void)write(crumbFd, line, (unsigned int)strlen(line));
    (void)fsync(crumbFd);
}

static int
allowed(unsigned long reg)
{
    unsigned long i;

    for (i = 0UL; i < sizeof allow / sizeof allow[0]; i++)
        if ((unsigned long)allow[i] == reg)
            return 1;
    return 0;
}

/* the tool's walk (check_replay.py walk()): 0 unless the packets end exactly at n and every
   PACKET0 register is allowed; *colour gets the last RB3D_COLOROFFSET value seen */
static int
walk(const unsigned long *w, unsigned long n, unsigned long *colour, unsigned long *badAt)
{
    unsigned long i = 0UL, h, cnt, reg, one, k, r;

    *colour = 0UL;
    while (i < n) {
        h = w[i];
        if ((h >> 30) == 0UL) {
            cnt = ((h >> 16) & 0x3fffUL) + 1UL;
            reg = (h & 0x1fffUL) << 2;
            one = (h >> 15) & 1UL;
            if (i + 1UL + cnt > n) {
                *badAt = i;
                return 0;
            }
            for (k = 0UL; k < cnt; k++) {
                r = one ? reg : reg + 4UL * k;
                if (!allowed(r)) {
                    *badAt = i;
                    return 0;
                }
                if (r == RB3D_COLOROFFSET)
                    *colour = w[i + 1UL + k];
            }
            i += 1UL + cnt;
        } else if ((h >> 30) == 3UL) {
            cnt = ((h >> 16) & 0x3fffUL) + 1UL;
            i += 1UL + cnt;
        } else if ((h >> 30) == 2UL) {
            i += 1UL;
        } else {
            *badAt = i;
            return 0;
        }
    }
    if (i != n) {
        *badAt = i;
        return 0;
    }
    return 1;
}

int
main(int argc, char **argv)
{
    const char *runid, *file, *crumbPath = 0;
    char *end;
    unsigned long maj, nwords = 0UL, reps = 0UL, stopAt = ~0UL, runNum, seed, k, colour, badAt = 0UL;
    unsigned long *words;
    struct stat st;
    osrdn_r7b_caps caps;
    osrdn_r7b_submit2 sub;
    FILE *f;
    int fd, rc, a, async = 0, heldFd = -1;

    if (argc < 6) {
        printf("RDNREPLAY usage: rdnreplay <runid> <major> <file> words=<N> reps=<R> [crumb=<path>] [stop=<k>]\n");
        return 2;
    }
    runid = argv[1];
    runNum = strtoul(runid, &end, 10);
    maj = strtoul(argv[2], &end, 0);
    file = argv[3];
    for (a = 4; a < argc; a++) {
        if (strncmp(argv[a], "words=", 6) == 0)
            nwords = strtoul(argv[a] + 6, &end, 10);
        else if (strncmp(argv[a], "reps=", 5) == 0)
            reps = strtoul(argv[a] + 5, &end, 10);
        else if (strncmp(argv[a], "crumb=", 6) == 0)
            crumbPath = argv[a] + 6;
        else if (strncmp(argv[a], "stop=", 5) == 0)
            stopAt = strtoul(argv[a] + 5, &end, 10);
        else if (strcmp(argv[a], "async=1") == 0)
            async = 1;                              /* G5-2: SUBMIT3, then one RETIRE */
        else {
            printf("RDNREPLAY usage: unknown argument %s\n", argv[a]);
            return 2;
        }
    }
    if (runNum == 0UL || nwords == 0UL || nwords > MAX_WORDS || reps == 0UL || reps > MAX_REPS) {
        printf("RDNREPLAY usage: runid non-zero, 1 <= words <= %lu, 1 <= reps <= %lu\n", MAX_WORDS, MAX_REPS);
        return 2;
    }

    /* the file, whole, before the device is touched */
    words = (unsigned long *)malloc(nwords * 4UL);
    if (words == 0) {
        printf("RDNREPLAY run=%s step=malloc\n", runid);
        return 2;
    }
    if ((f = fopen(file, "r")) == 0) {
        printf("RDNREPLAY run=%s step=fopen errno=%d\n", runid, errno);
        return 2;
    }
    if (fread((char *)words, 4, (int)nwords, f) != (int)nwords) {
        printf("RDNREPLAY run=%s step=fread short (want %lu words)\n", runid, nwords);
        (void)fclose(f);
        return 2;
    }
    (void)fclose(f);

    /* the node and CAPS, as rdnr7dev.c */
    if (stat(NODE, &st) == 0) {
        if ((st.st_mode & S_IFMT) != S_IFCHR || (unsigned long)(st.st_rdev >> 8) != maj) {
            printf("RDNREPLAY run=%s step=node exists with mode %o rdev %x, not char major %lu\n",
                   runid, (unsigned)st.st_mode, (unsigned)st.st_rdev, maj);
            return 3;
        }
    } else if (mknod(NODE, S_IFCHR | 0600, (int)((maj << 8) | 0UL)) != 0) {
        printf("RDNREPLAY run=%s step=mknod errno=%d\n", runid, errno);
        return 3;
    }
    if ((fd = open(NODE, NODE_RDWR)) < 0) {
        printf("RDNREPLAY run=%s step=open errno=%d\n", runid, errno);
        return 3;
    }
    memset((char *)&caps, 0, sizeof caps);
    if (ioctl(fd, (int)OSRDN_R7B_IOC_CAPS, (char *)&caps) != 0) {
        printf("RDNREPLAY run=%s step=caps errno=%d\n", runid, errno);
        (void)close(fd);
        return 4;
    }
    printf("RDNREPLAY run=%s step=caps magic=%08lx ver=%lu max=%lu build=%08lx ready=%lu cprunning=%lu winstart=%08lx\n",
           runid, caps.magic, caps.version, caps.maxWords, caps.build, caps.ready, caps.cpRunning, caps.winStart);
    (void)close(fd);                /* C2: the driver's open is a binary latch; the repetitions open again */
    if (caps.magic != OSRDN_R7B_MAGIC || caps.version != OSRDN_R7B_VERSION || !caps.ready || !caps.cpRunning ||
        caps.maxWords < nwords) {
        printf("RDNREPLAY run=%s step=caps-gate refused (magic/version/ready/cprunning/max)\n", runid);
        return 4;
    }

    /* the stream's own gates */
    if (!walk(words, nwords, &colour, &badAt)) {
        printf("RDNREPLAY run=%s step=walk refused at word %lu (boundary, register or header)\n", runid, badAt);
        return 7;
    }
    if (colour != caps.winStart) {
        printf("RDNREPLAY run=%s step=win refused: stream colour %08lx, this boot's winStart %08lx (no relocation)\n",
               runid, colour, caps.winStart);
        return 7;
    }
    printf("RDNREPLAY run=%s step=gates words=%lu colour=%08lx reps=%lu\n", runid, nwords, colour, reps);

    if (crumbPath != 0) {
        crumbFd = open(crumbPath, CRUMB_FLAGS, 0644);
        if (crumbFd < 0) {
            printf("RDNREPLAY run=%s step=crumb-open errno=%d\n", runid, errno);
            return 2;
        }
    }

    /* G5-2: async=1 HOLDS one descriptor across the repetitions, as the library does in present mode.
       The driver's last close retires what is in flight (docs/G5_2_ASYNC_SUBMIT_PLAN.md 2-5), so an
       open/close per repetition would wait at every close and measure nothing accepted. */
    heldFd = -1;
    if (async && (heldFd = open(NODE, NODE_RDWR)) < 0) {
        printf("RDNREPLAY run=%s step=open (held) errno=%d\n", runid, errno);
        return 3;
    }
    for (k = 0UL; k < reps; k++) {
        seed = (runNum % 4000000UL) * 1000UL + k + 1UL;     /* C3: never 0, never the previous call's */
        crumb("rep", k, seed, ~0UL, 0UL, 0UL);
        if (k == stopAt) {
            printf("RDNREPLAY run=%s step=stop k=%lu (before its ioctl)\n", runid, k);
            return 0;
        }
        if (heldFd >= 0)
            fd = heldFd;
        else if ((fd = open(NODE, NODE_RDWR)) < 0) {
            printf("RDNREPLAY run=%s step=open k=%lu errno=%d\n", runid, k, errno);
            return 3;
        }
        memset((char *)&sub, 0, sizeof sub);
        sub.magic = OSRDN_R7B_MAGIC;                /* the library's fields, in its order (OSRDNMesaTri.c) */
        sub.version = OSRDN_R7B_VERSION;
        sub.nwords = nwords;
        sub.seed = seed;
        sub.words = (unsigned long)words;
        sub.status = 0UL;
        sub.why = 0UL;
        sub.at = 0UL;
        sub.word = 0UL;
        sub.drawn = 0UL;
        rc = ioctl(fd, async ? (int)OSRDN_R7B_IOC_SUBMIT3 : (int)OSRDN_R7B_IOC_SUBMIT2, (char *)&sub);
        if (heldFd < 0)
            (void)close(fd);
        if (rc != 0) {                              /* C4: the reply block is not valid now */
            printf("RDNREPLAY run=%s step=submit k=%lu errno=%d (reply not valid)\n", runid, k, errno);
            crumb("ioctl", k, (unsigned long)errno, ~0UL, 0UL, 0UL);
            return 6;
        }
        crumb("done", k, sub.status, sub.why, sub.at, sub.drawn);
        if (sub.status != 0UL || sub.why != 0UL || sub.drawn == 0UL) {
            printf("RDNREPLAY run=%s step=submit k=%lu status=%lu why=%lu at=%lu word=%08lx drawn=%lu REFUSED\n",
                   runid, k, sub.status, sub.why, sub.at, sub.word, sub.drawn);
            return 8;
        }
    }
    printf("RDNREPLAY run=%s step=done reps=%lu words=%lu last: status=%lu why=%lu at=%lu drawn=%lu async=%d\n",
           runid, reps, nwords, sub.status, sub.why, sub.at, sub.drawn, async);
    if (async) {
        osrdn_r7b_retire rb;

        memset((char *)&rb, 0, sizeof rb);
        rb.magic = OSRDN_RETIRE_MAGIC;
        rb.version = OSRDN_RETIRE_VERSION;
        rc = ioctl(heldFd, (int)OSRDN_R7B_IOC_RETIRE, (char *)&rb);
        (void)close(heldFd);
        printf("RDNREPLAY run=%s step=retire rc=%d status=%lu waited=%lu us=%lu asubmits=%lu lost=%lu cprc=%ld\n",
               runid, rc, rb.status, rb.waited, rb.us, rb.asubmits, rb.lost, (long)rb.rc);
        if (rc != 0 || rb.status != 0UL)
            return 8;
    }
    return 0;
}
