#!/usr/bin/env python3
"""Generate OSRDNDisplay_reloc.tproj/osrdn_cp_ucode.h, the R200 CP microcode the
RV280 loads (docs/R5_PLAN.md 1 S1), from FreeBSD's radeon_microcode.h, keeping
AMD's notice.

  gen_ucode.py            write the header
  gen_ucode.py --check    the header on disk equals a fresh generation, and its
                          256 pairs in load order (DATAH = cp[i][1], DATAL =
                          cp[i][0]) equal linux-firmware radeon/R200_cp.bin as
                          big-endian words -- a second source, not the same one
                          read twice; then mutations of the header must fail

The header is data only; the driver writes it with the load loop in osrdn_cp.m.
"""

import hashlib
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(os.path.dirname(HERE))
UP = os.path.join(PROJ, 'ref', 'upstream')
SRC = os.path.join(UP, 'freebsd-stable9', 'sys', 'dev', 'drm', 'radeon_microcode.h')
BIN = os.path.join(UP, 'linux-firmware', 'radeon', 'R200_cp.bin')
BIN_SHA256 = '2b7b4bf988c3f7c69f98ea2ec6c4155fa85e2c9d5f5aee77912baaf50f5f7bac'
OUT = os.path.join(PROJ, 'OSRDNDisplay', 'OSRDNDisplay_reloc.tproj', 'osrdn_cp_ucode.h')


def source_pairs():
    text = open(SRC).read()
    start = text.index('R200_cp_microcode[][2]')
    body = text[text.index('{', start) + 1:]
    body = body[:body.index('};')]
    pairs = [(int(a, 0), int(b, 0)) for a, b in
             re.findall(r'\{\s*(0x[0-9a-fA-F]+|0+)\s*,\s*(0x[0-9a-fA-F]+|0+)\s*\}', body)]
    if len(pairs) != 256:
        sys.exit('expected 256 pairs, found %d' % len(pairs))
    return pairs


def notice():
    text = open(SRC).read()
    block = text[text.index('/*-'):text.index('*/') + 2]
    return block.replace('/*-', '/*', 1)


def generate():
    pairs = source_pairs()
    lines = [notice(), '',
             '/*',
             ' * osrdn_cp_ucode.h - GENERATED by tools/r5/gen_ucode.py from FreeBSD',
             ' * sys/dev/drm/radeon_microcode.h R200_cp_microcode (the table FreeBSD loads for',
             ' * CHIP_RV280, radeon_cp.c radeon_cp_load_microcode).  Do not edit; regenerate.',
             ' * Column 0 goes to CP_ME_RAM_DATAL, column 1 to CP_ME_RAM_DATAH, DATAH first.',
             ' * tools/r5/gen_ucode.py --check holds it to linux-firmware radeon/R200_cp.bin.',
             ' */',
             '',
             '#ifndef OSRDN_CP_UCODE_H',
             '#define OSRDN_CP_UCODE_H',
             '',
             '#define OSRDN_CP_UCODE_PAIRS    256',
             '',
             'static const unsigned long osrdnCpUcode[OSRDN_CP_UCODE_PAIRS][2] = {']
    for k, (a, b) in enumerate(pairs):
        lines.append('    { 0x%08xUL, 0x%08xUL }%s' % (a, b, ',' if k < 255 else ''))
    lines += ['};', '', '#endif /* OSRDN_CP_UCODE_H */', '']
    return '\n'.join(lines)


def header_pairs(text):
    body = text[text.index('osrdnCpUcode[OSRDN_CP_UCODE_PAIRS][2] = {'):]
    return [(int(a, 16), int(b, 16)) for a, b in re.findall(r'\{ 0x([0-9a-f]{8})UL, 0x([0-9a-f]{8})UL \}', body)]


def judge(text):
    p = []
    pairs = header_pairs(text)
    if len(pairs) != 256:
        return ['the header holds %d pairs' % len(pairs)]
    data = open(BIN, 'rb').read()
    if hashlib.sha256(data).hexdigest() != BIN_SHA256 or len(data) != 2048:
        return ['R200_cp.bin is not the recorded file']
    words = struct.unpack('>512I', data)
    load = [w for a, b in pairs for w in (b, a)]          # DATAH = cp[i][1] first, then DATAL
    if list(words) != load:
        bad = [i for i in range(512) if words[i] != load[i]]
        p.append('%d of 512 words differ from R200_cp.bin in load order (first word %d)' % (len(bad), bad[0]))
    swapped = [w for a, b in pairs for w in (a, b)]
    if list(words) == swapped:
        p.append('the header also equals the swapped order: the check cannot tell the columns apart')
    if 'Advanced Micro Devices' not in text or 'Permission is hereby granted' not in text:
        p.append('the AMD notice is missing')
    return p


def main():
    if sys.argv[1:] == ['--check']:
        fails = 0
        text = open(OUT).read()
        fresh = generate()
        if text != fresh:
            print('  FAIL osrdn_cp_ucode.h differs from a fresh generation')
            fails += 1
        else:
            print('  ok   osrdn_cp_ucode.h equals a fresh generation from radeon_microcode.h')
        p = judge(text)
        for x in p:
            print('  FAIL %s' % x)
        print('  %-4s 256 pairs in load order equal linux-firmware R200_cp.bin (sha256 %s...)'
              % ('FAIL' if p else 'ok', BIN_SHA256[:8]))
        fails += len(p)
        pairs = header_pairs(text)
        muts = [('two columns swapped in pair 3', lambda s: s.replace(
                    '{ 0x%08xUL, 0x%08xUL }' % pairs[3], '{ 0x%08xUL, 0x%08xUL }' % (pairs[3][1], pairs[3][0]), 1)),
                ('pair 255 dropped', lambda s: s.replace(',\n    { 0x%08xUL, 0x%08xUL }\n};' % pairs[255], '\n};', 1)),
                ('one bit flipped in pair 100', lambda s: s.replace(
                    '{ 0x%08xUL, 0x%08xUL }' % pairs[100], '{ 0x%08xUL, 0x%08xUL }' % (pairs[100][0] ^ 1, pairs[100][1]), 1)),
                ('the notice removed', lambda s: s.replace('Permission is hereby granted', 'Permission', 1))]
        for label, f in muts:
            m = f(text)
            caught = m != text and bool(judge(m))
            print('  %-4s mutation %s' % ('ok' if caught else 'FAIL', label))
            fails += 0 if caught else 1
        print('gen_ucode: %s' % ('PASS' if not fails else 'FAIL (%d)' % fails))
        return 1 if fails else 0
    open(OUT, 'w').write(generate())
    print('wrote %s' % OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
