#!/usr/bin/env python3
"""The client-side verifier, GENERATED from the kernel's (G4-2 B0, docs/G4_2_BATCH_PLAN.md 2).

  gen_r7verify.py                write mesa/OSRDNMesaVerify.c and .h
  gen_r7verify.py --check        regenerate and compare (check-all)
  gen_r7verify.py --self-test    the extraction's own invariants

The kernel's cpR7Verify and its helpers read four fields of osrdn_cp_state (r7WinStart, r7WinEnd
to read, r7At, r7Word to write) and nothing else of the kernel; so the library's copy is the
kernel's TEXT, sliced out of osrdn_cp.m with its constants and its allow-list, with the state type
renamed to a four-field struct.  Nothing is typed here: a rule added to the kernel appears in the
library at the next regeneration, and --check refuses a stale copy.  tools/mesa/sim_verify.py then
runs the oracle's cases through the generated unit and expects the kernel's verdicts.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(os.path.dirname(HERE))
TPROJ = os.path.join(PROJ, 'OSRDNDisplay', 'OSRDNDisplay_reloc.tproj')
CP_M = os.path.join(TPROJ, 'osrdn_cp.m')
CP_H = os.path.join(TPROJ, 'osrdn_cp.h')
OUT_C = os.path.join(PROJ, 'mesa', 'OSRDNMesaVerify.c')
OUT_H = os.path.join(PROJ, 'mesa', 'OSRDNMesaVerify.h')

FUNC_BEGIN = '/* R7a (docs/R7_PLAN.md 4): the client\'s staged stream, and the verifier that decides whether any'
FUNC_END = '/* RESET and APPEND.  The kernel copies every word into its own buffer as it arrives, so the words'
TABLE_BEGIN = '/* R7a (docs/R7_PLAN.md 4): the registers a client may write'
MASK_BEGIN = '/* R7a (docs/R7_PLAN.md 4): the value masks, the vertex format\'s measured fields, and VF_CNTL.'
MASK_END = '#define C_P3_IMMD(n)'
FIELDS = ('r7WinStart', 'r7WinEnd', 'r7At', 'r7Word')
FORBIDDEN = ('IOLog', 'rdnMmio', 'cpR7Buf', 'cpR6State', 'cpRefused', 'IODelay', 'c->subWords', 'c->why')


def slice_between(text, begin, end):
    a = text.index(begin)
    b = text.index(end, a)
    return text[a:b]


def generate():
    m = open(CP_M).read()
    h = open(CP_H).read()
    funcs = slice_between(m, FUNC_BEGIN, FUNC_END).rstrip() + '\n'
    # the staging buffer is declared between the comment and the first function: kernel-only, and not
    # read by any verifier function (a rule below refuses any other cpR7Buf mention)
    funcs = '\n'.join(l for l in funcs.split('\n') if 'static unsigned long cpR7Buf[' not in l)
    table = slice_between(m, TABLE_BEGIN, FUNC_BEGIN).rstrip() + '\n'
    masks = slice_between(m, MASK_BEGIN, MASK_END).rstrip() + '\n'
    # the C_* register names the functions use, each with the kernel's own define
    names = sorted(set(re.findall(r'\b(C_[A-Z0-9_]+)\b', funcs)) - set(re.findall(r'#define\s+(C_[A-Z0-9_]+)', masks)))
    regs = []
    for n in names:
        mm = re.search(r'^#define\s+%s\s+(\S+)' % re.escape(n), m, re.M)
        if not mm:
            raise RuntimeError('no define for %s in osrdn_cp.m' % n)
        regs.append('#define %-23s %s' % (n, mm.group(1)))
    whys = re.findall(r'^#define\s+(CP_R7_WHY_\w+)\s+(\d+)', h, re.M)
    bmax = re.search(r'^#define\s+CP_R7_BATCH_MAX\s+(\d+)', h, re.M).group(1)
    # the defaults the kernel hands the verifier at its call site (osrdn_cp.m: cpR6ColorOff/cpR6DepthOff/
    # CP_R6_PITCH): the library must judge with the same three, so they travel in the header
    defs = []
    for k in ('CP_R6_DEPTH_OFF', 'CP_R6_COLOR_OFF', 'CP_R6_PITCH'):
        mm = re.search(r'^#define\s+%s\s+(\S+)' % k, h, re.M)
        if not mm:
            raise RuntimeError('osrdn_cp.h has no %s' % k)
        defs.append('#define OSRDN_R7V_DEF_%-13s %s' % (k[6:], mm.group(1)))
    call = 'cpR7Verify(c, cpR7Buf, c->subWords, c->winStart + cpR6ColorOff(cs), c->winStart + cpR6DepthOff(cs), CP_R6_PITCH)'
    if re.sub(r'\s+', ' ', call) not in re.sub(r'\s+', ' ', m):
        raise RuntimeError('the kernel call site changed; the three defaults may no longer be the ones emitted')
    for f in FIELDS:
        if ('c->%s' % f) not in funcs:
            raise RuntimeError('the verifier no longer uses c->%s: the four-field struct is stale' % f)
    for bad in FORBIDDEN:
        if bad in funcs:
            raise RuntimeError('the verifier reaches for %s: it is not pure any more' % bad)
    other = sorted(set(re.findall(r'c->(\w+)', funcs)) - set(FIELDS))
    if other:
        raise RuntimeError('the verifier reads state fields outside the four: %s' % other)
    body = funcs.replace('const osrdn_cp_state *c', 'const osrdn_r7v *c').replace('osrdn_cp_state *c', 'osrdn_r7v *c')
    if 'osrdn_cp_state' in body:
        raise RuntimeError('an osrdn_cp_state mention survived the rename')
    hdr = ['/*',
           ' * OSRDNMesaVerify.h - the client-side copy of the kernel\'s stream verifier (G4-2 B0).',
           ' * GENERATED by tools/mesa/gen_r7verify.py from OSRDNDisplay/OSRDNDisplay_reloc.tproj/osrdn_cp.m',
           ' * and osrdn_cp.h -- do not edit; regenerate.  The codes are the kernel\'s CP_R7_WHY_*.',
           ' */',
           '#ifndef OSRDN_MESA_VERIFY_H', '#define OSRDN_MESA_VERIFY_H', '']
    hdr += ['#define %-23s %s' % (n, v) for n, v in whys]
    hdr += ['#define CP_R7_BATCH_MAX         %s' % bmax, '',
            '/* what the kernel\'s prefix leaves (osrdn_cp.h): the library passes winStart + these as defC/defZ',
            '   and the pitch as defPitch, as the kernel\'s own call site does */'] + defs + ['',
            '/* the verdict on a client stream of n words for a window [winStart, winEnd) whose prefix left the',
            '   colour surface at defC, the depth surface at defZ, both with pitch defPitch: CP_R7_WHY_OK, or the',
            '   rule that refused, with *at the word it stopped at and *word that word */',
            'unsigned long osrdn_r7_verify(unsigned long winStart, unsigned long winEnd, unsigned long defC,',
            '                              unsigned long defZ, unsigned long defPitch,',
            '                              const unsigned long *w, unsigned long n,',
            '                              unsigned long *at, unsigned long *word);', '',
            '#endif /* OSRDN_MESA_VERIFY_H */', '']
    src = ['/*',
           ' * OSRDNMesaVerify.c - the kernel\'s stream verifier, in the library (G4-2 B0,',
           ' * docs/G4_2_BATCH_PLAN.md 2).  GENERATED by tools/mesa/gen_r7verify.py from the kernel\'s',
           ' * osrdn_cp.m: the functions below are that file\'s text with the kernel state type renamed to the',
           ' * four fields they use.  Do not edit; regenerate (check-all refuses a stale copy).',
           ' */',
           '#include "OSRDNMesaVerify.h"', '',
           'typedef struct {',
           '    unsigned long r7WinStart, r7WinEnd;     /* the window, read */',
           '    unsigned long r7At, r7Word;             /* where a refusal stopped, written */',
           '} osrdn_r7v;', '',
           '/* the register addresses the kernel names (osrdn_cp.m) */'] + regs + ['', masks.rstrip('\n'), '', table.rstrip('\n'), '', body.rstrip('\n'), '',
           'unsigned long',
           'osrdn_r7_verify(unsigned long winStart, unsigned long winEnd, unsigned long defC,',
           '                unsigned long defZ, unsigned long defPitch,',
           '                const unsigned long *w, unsigned long n, unsigned long *at, unsigned long *word)',
           '{',
           '    osrdn_r7v v;',
           '    unsigned long why;',
           '',
           '    v.r7WinStart = winStart;',
           '    v.r7WinEnd = winEnd;',
           '    v.r7At = 0UL;',
           '    v.r7Word = 0UL;',
           '    why = cpR7Verify(&v, w, n, defC, defZ, defPitch);',
           '    if (at != 0)',
           '        *at = v.r7At;',
           '    if (word != 0)',
           '        *word = v.r7Word;',
           '    return why;',
           '}', '']
    return '\n'.join(src), '\n'.join(hdr)


def self_test():
    c, h = generate()
    fails = 0

    def ok(cond, what):
        nonlocal fails
        fails += 0 if cond else 1
        print('  %-4s %s' % ('ok' if cond else 'FAIL', what))
    for fn in ('cpR7RegAllowed', 'cpR7ValueAllowed', 'cpR7TextureBytes', 'cpR7TextureFits', 'cpR7VertexWords',
               'cpR7SurfaceFits', 'cpR7SurfacesOk', 'cpR7Verify'):
        ok(('\n%s(' % fn) in c, 'the kernel function %s is in the copy' % fn)
    ok('cpR7Stage' not in c, 'the staging (kernel-only) is not')
    ok('static const unsigned short cpR7Allow[' in c, 'the allow-list travels with it')
    ok(all(('#define %s' % n) in c for n in ('CP_R7_TXO_LOW_MASK', 'CP_R7_PP_MISC_FIELDS', 'C_PP_TXOFFSET_0', 'C_RE_WIDTH_HEIGHT')),
       'the masks and the register names travel with it')
    ok('osrdn_cp_state' not in c and 'osrdn_r7v' in c, 'the state type is the four-field struct')
    ok(not any(b in c for b in FORBIDDEN), 'no kernel symbol survives')
    ok('CP_R7_WHY_SURFACE' in h and 'CP_R7_BATCH_MAX' in h, 'the header carries the codes and the limit')
    ok(all(('#define OSRDN_R7V_DEF_%s' % k) in h for k in ('DEPTH_OFF', 'COLOR_OFF', 'PITCH')),
       'the header carries the three defaults of the kernel call site')
    print('gen_r7verify self-test: %s' % ('PASS' if not fails else 'FAIL (%d)' % fails))
    return 1 if fails else 0


def main():
    if '--self-test' in sys.argv:
        return self_test()
    c, h = generate()
    if '--check' in sys.argv:
        oc = open(OUT_C).read() if os.path.exists(OUT_C) else ''
        oh = open(OUT_H).read() if os.path.exists(OUT_H) else ''
        if oc == c and oh == h:
            print('gen_r7verify --check: PASS (regenerated identically, %d lines)' % c.count('\n'))
            return 0
        print('gen_r7verify --check: FAIL (mesa/OSRDNMesaVerify.[ch] are not what osrdn_cp.m generates -- regenerate)')
        return 1
    open(OUT_C, 'w').write(c)
    open(OUT_H, 'w').write(h)
    print('wrote mesa/OSRDNMesaVerify.c (%d lines) and .h' % c.count('\n'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
