/*
 * osrdn_expect.h - GENERATED by tools/r2b0/gen_expect_r2b0.py.  Do not edit.
 *
 * Gate expectations for the R2b-0 record (docs/R2B0_IMPL_PLAN.md 4-4), taken
 * from raw logs and checked against values a person wrote:
 *   R1  build/r1/rdn-r1-789453017.log sha256 3ede696609722b72
 *   R2a build/r2a/789467668/rdn-r2a-789467668.log sha256 e97c433f28e14a5e
 * Only osrdn_record.m imports this file.
 */

typedef struct {
    const char     *gate;
    const char     *name;
    unsigned int    offset;
    unsigned long   want;
} osrdn_expect;

#define OSRDN_EXPECT_R1_COUNT   4
static const osrdn_expect osrdnExpectR1[OSRDN_EXPECT_R1_COUNT] = {
    { "mcfb", "MC_FB_LOCATION", 0x0148, 0x1fff0000UL },
    { "mcagp", "MC_AGP_LOCATION", 0x014c, 0x27ff2000UL },
    { "hostpath", "HOST_PATH_CNTL", 0x0130, 0x70000000UL },
    { "surface", "SURFACE_CNTL", 0x0b00, 0x00000100UL }
};

#define OSRDN_EXPECT_R2A_COUNT  14
static const osrdn_expect osrdnExpectR2a[OSRDN_EXPECT_R2A_COUNT] = {
    { "ovr_clr", "OVR_CLR", 0x0230, 0x00000000UL },
    { "ovr_wid_left_right", "OVR_WID_LEFT_RIGHT", 0x0234, 0x00000000UL },
    { "ovr_wid_top_bottom", "OVR_WID_TOP_BOTTOM", 0x0238, 0x00000000UL },
    { "ov0_scale_cntl", "OV0_SCALE_CNTL", 0x0420, 0x807f0000UL },
    { "subpic_cntl", "SUBPIC_CNTL", 0x0540, 0x00000000UL },
    { "viph_control", "VIPH_CONTROL", 0x0c40, 0x00000000UL },
    { "i2c_cntl_1", "I2C_CNTL_1", 0x0094, 0x00000000UL },
    { "cap0_trig_cntl", "CAP0_TRIG_CNTL", 0x0950, 0x00000000UL },
    { "cap1_trig_cntl", "CAP1_TRIG_CNTL", 0x09c0, 0x00000000UL },
    { "tv_dac_cntl", "TV_DAC_CNTL", 0x088c, 0x07660142UL },
    { "disp_hw_debug", "DISP_HW_DEBUG", 0x0d14, 0x00020000UL },
    { "disp_output_cntl", "DISP_OUTPUT_CNTL", 0x0d64, 0x10000000UL },
    { "dac_cntl2", "DAC_CNTL2", 0x007c, 0x00000000UL },
    { "crtc_offset_cntl", "CRTC_OFFSET_CNTL", 0x0228, 0x10000000UL }
};
