#!/usr/bin/env python3
"""Generate OSRDNDisplay's gate expectation header from raw logs (docs/R2B0_IMPL_PLAN.md 4-4, 6-1).

  gen_expect_r2b0.py            write OSRDNDisplay/OSRDNDisplay_reloc.tproj/osrdn_expect.h
  gen_expect_r2b0.py --check    exit 1 unless the file on disk equals what would be written

The values come from the RAW R1 and R2a logs, parsed by the R1 and R2a
parsers, and every one must equal the value a person wrote in a document
(HUMAN below, with the line it was copied from).  A disagreement stops the
generator: an expectation is never a copy of a generated file.
"""

import hashlib
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(PROJ, 'OSRDNDisplay', 'OSRDNDisplay_reloc.tproj', 'osrdn_expect.h')
R1_LOG = os.path.join(PROJ, 'build', 'r1', 'rdn-r1-789453017.log')
R1_RUNID = '789453017'
R2A_LOG = os.path.join(PROJ, 'build', 'r2a', '789467668', 'rdn-r2a-789467668.log')
R2A_RUNID = '789467668'


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


pr1 = _load('parse_r1_gen', os.path.join(PROJ, 'tools', 'r1', 'parse_r1.py'))
pr2 = _load('parse_r2a_gen', os.path.join(PROJ, 'tools', 'r2a', 'parse_r2a.py'))

# gate name -> register, in the order the driver evaluates them
R1_GATES = [('mcfb', 'MC_FB_LOCATION'), ('mcagp', 'MC_AGP_LOCATION'),
            ('hostpath', 'HOST_PATH_CNTL'), ('surface', 'SURFACE_CNTL')]
R2A_GATES = list(pr2.INTERFERING) + ['TV_DAC_CNTL', 'DISP_HW_DEBUG', 'DISP_OUTPUT_CNTL', 'DAC_CNTL2',
                                      'CRTC_OFFSET_CNTL']

# (value, where a person wrote it)
HUMAN = {
    'MC_FB_LOCATION': (0x1fff0000, 'docs/R1_RESULT.md 36'),
    'MC_AGP_LOCATION': (0x27ff2000, 'docs/R1_RESULT.md 36'),
    'HOST_PATH_CNTL': (0x70000000, 'docs/R1_RESULT.md 35'),
    'SURFACE_CNTL': (0x00000100, 'docs/R1_RESULT.md 43'),
    'OV0_SCALE_CNTL': (0x807f0000, 'docs/R2_FIRST_LIGHT_PLAN.md 50 (G6), 219 (step 0)'),
    'TV_DAC_CNTL': (0x07660142, 'docs/R2_FIRST_LIGHT_PLAN.md 219'),
    'DISP_HW_DEBUG': (0x00020000, 'docs/R2_FIRST_LIGHT_PLAN.md 219'),
    'DISP_OUTPUT_CNTL': (0x10000000, 'docs/R2_FIRST_LIGHT_PLAN.md 219'),
    'DAC_CNTL2': (0x00000000, 'docs/R2_FIRST_LIGHT_PLAN.md 219'),
    'CRTC_OFFSET_CNTL': (0x10000000, 'docs/R2_FIRST_LIGHT_PLAN.md 51 (G7), 219'),
}
for _n in pr2.INTERFERING:
    if _n != 'OV0_SCALE_CNTL':
        HUMAN[_n] = (0, 'docs/R2_FIRST_LIGHT_PLAN.md 50 (G6: the other eight 0), 219')


def sha(path):
    return hashlib.sha256(open(path, 'rb').read()).hexdigest()


def values():
    """{register: value} from the raw logs, and a list of disagreements."""
    bad = []
    r1text = open(R1_LOG, errors='replace').read()
    r2text = open(R2A_LOG, errors='replace').read()
    f1, n1, b1, e1 = pr1.parse(r1text, R1_RUNID)
    f2, n2, b2, e2 = pr2.parse(r2text, R2A_RUNID)
    if b1 is None or e1 is None or f1['malformed']:
        bad.append('R1 log %s is not a complete run' % R1_RUNID)
    if b2 is None or e2 is None or f2['malformed']:
        bad.append('R2a log %s is not a complete run' % R2A_RUNID)
    got = {}
    for _, reg in R1_GATES:
        off, val = f1['reg'][reg]
        if off != pr2.REGS[reg]:
            bad.append('%s logged at %04x, table %04x' % (reg, off, pr2.REGS[reg]))
        got[reg] = ('R1', off, val)
    for reg in R2A_GATES:
        off, val = f2['reg'][reg]
        if off != pr2.REGS[reg]:
            bad.append('%s logged at %04x, table %04x' % (reg, off, pr2.REGS[reg]))
        got[reg] = ('R2a', off, val)
    for reg, (src, off, val) in sorted(got.items()):
        want, where = HUMAN[reg]
        if val != want:
            bad.append('%s: %s log %08x, a person wrote %08x (%s)' % (reg, src, val, want, where))
    if set(HUMAN) != set(got):
        bad.append('HUMAN covers %s, gates cover %s' % (sorted(HUMAN), sorted(got)))
    return got, bad


def render(got):
    out = []
    out.append('/*')
    out.append(' * osrdn_expect.h - GENERATED by tools/r2b0/gen_expect_r2b0.py.  Do not edit.')
    out.append(' *')
    out.append(' * Gate expectations for the R2b-0 record (docs/R2B0_IMPL_PLAN.md 4-4), taken')
    out.append(' * from raw logs and checked against values a person wrote:')
    out.append(' *   R1  %s sha256 %s' % (os.path.relpath(R1_LOG, PROJ), sha(R1_LOG)[:16]))
    out.append(' *   R2a %s sha256 %s' % (os.path.relpath(R2A_LOG, PROJ), sha(R2A_LOG)[:16]))
    out.append(' * Only osrdn_record.m imports this file.')
    out.append(' */')
    out.append('')
    out.append('typedef struct {')
    out.append('    const char     *gate;')
    out.append('    const char     *name;')
    out.append('    unsigned int    offset;')
    out.append('    unsigned long   want;')
    out.append('} osrdn_expect;')
    out.append('')
    out.append('#define OSRDN_EXPECT_R1_COUNT   %d' % len(R1_GATES))
    out.append('static const osrdn_expect osrdnExpectR1[OSRDN_EXPECT_R1_COUNT] = {')
    rows = ['    { "%s", "%s", 0x%04x, 0x%08xUL }' % (g, reg, got[reg][1], got[reg][2]) for g, reg in R1_GATES]
    out.append(',\n'.join(rows))
    out.append('};')
    out.append('')
    out.append('#define OSRDN_EXPECT_R2A_COUNT  %d' % len(R2A_GATES))
    out.append('static const osrdn_expect osrdnExpectR2a[OSRDN_EXPECT_R2A_COUNT] = {')
    rows = ['    { "%s", "%s", 0x%04x, 0x%08xUL }' % (reg.lower(), reg, got[reg][1], got[reg][2]) for reg in R2A_GATES]
    out.append(',\n'.join(rows))
    out.append('};')
    return '\n'.join(out) + '\n'


def main(argv):
    got, bad = values()
    if bad:
        for b in bad:
            print('gen_expect_r2b0: FAIL', b)
        return 1
    text = render(got)
    if argv[1:] == ['--check']:
        cur = open(OUT).read() if os.path.exists(OUT) else ''
        if cur != text:
            print('gen_expect_r2b0: FAIL %s differs from the generator output' % os.path.relpath(OUT, PROJ))
            return 1
        print('gen_expect_r2b0: PASS (%d R1 and %d R2a expectations, each equal to a written value)'
              % (len(R1_GATES), len(R2A_GATES)))
        return 0
    if argv[1:]:
        print(__doc__)
        return 2
    open(OUT, 'w').write(text)
    print('wrote', os.path.relpath(OUT, PROJ))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
