/*
 * rdnr7dev.c - R7b: submit one client stream through the CHARACTER DEVICE
 * (docs/R7_PLAN.md 10).  Pure C.
 *
 * Build on the target:
 *   cc -O -Wall -o rdnr7dev rdnr7dev.c
 *
 * There is no -lDriver and no #import on purpose.  R7a's tool reached the
 * driver through IODeviceMaster, which is Objective-C; the Mesa acceleration
 * library cannot link Objective-C, so the whole point of this one is to prove
 * the same verifier, the same buffer and the same draw are reachable with
 * nothing but open, ioctl and mmap.  If this file ever needs an Objective-C
 * header, R7b has failed and the failure should be loud.
 *
 * Usage:
 *   rdnr7dev <runid> <major> <case> [n=<count>] [unknown] [hold]
 *     major    the driver's character major (the driver pins it; 38 on this card)
 *     case     0 .. CP_R7_CASE_COUNT-1, the streams tools/r7/verify_oracle.py built
 *     n=<count>  submit a different count than the case has, to reach the kernel's
 *                own limit checks before the verifier (0 and 2017 are the ones)
 *     unknown  send a command in this group that the driver does not answer, and
 *              stop -- gate E: it must be refused AND leave its number in the log
 *     hold     open the node a SECOND time while this one holds it, and stop --
 *              gate C: it must be refused.  That it changed nothing is what the
 *              runs after it show, so this mode does not submit.
 *
 * The stream table is GENERATED (tools/r7/verify_oracle.py --c-cases) with
 * win = 0; this boot's winStart comes back from CAPS and is added to the words
 * the generated mask marks.  Nothing about a boot is baked in.
 *
 * Exit codes:
 *   0  submitted (whatever the verdict)   2  usage
 *   3  mknod/open failed                  4  CAPS refused or disagrees with this build
 *   5  mmap refused                       6  SUBMIT could not be sent at all
 *
 * Every line starts "RDNR7B ".
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <mach/mach.h>

#include "osrdn_r7b.h"

/* this is the 4.2BSD mmap: the address must be the caller's already, so the
   place is vm_allocated first and then mapped over (R4c, and the Matrox
   probe's OSMGAMesaProbe.c:275-292 records the same discovery) */
extern caddr_t mmap(caddr_t, int, int, int, int, off_t);
/* this libc's headers declare none of these, and an implicit declaration is a
   guess: say what they are rather than let the compiler assume */
extern int mknod(const char *, int, int);
extern int open(const char *, int, ...);
extern int ioctl(int, int, char *);
extern int close(int);

/* the SAME node R4c's tool uses: one major, one minor, one device.  A node of
   its own would make rdnr4map's hygiene check ("no other node reaches this
   major") refuse on the next run, for no gain -- it is the same device. */
#define NODE            "/dev/rdnvram0"
#define IS_CHR(m)       (((m) & S_IFMT) == S_IFCHR)   /* S_ISCHR is POSIX-only in these headers */
#define PROT_RW         3               /* PROT_READ | PROT_WRITE */
#define MAP_SHARED_     1

/* <<<GENERATED CASES>>> */
/* R7a: the streams the simulator stages, and the rule each one must trip.  GENERATED by
   tools/r7/verify_oracle.py --c-cases; nothing here is typed by hand. */
#define CP_R7_POOL_WORDS 1476
#define CP_R7_SIM_WIN_BYTES 0x1000000UL   /* M3h: the client window the cases are built for */
#define CP_R7_CASE_COUNT 37
static const unsigned long cpR7Pool[1476] = {
    0x0000070eUL, 0x00001000UL, 0x00000714UL, 0x00000002UL,
    0x0000070fUL, 0x00001902UL, 0x0000070bUL, 0x42227072UL,
    0x0000075fUL, 0x00000000UL, 0x00000761UL, 0xffffffffUL,
    0x00000713UL, 0x480055deUL, 0x0000082cUL, 0x00000300UL,
    0x00000822UL, 0x00000803UL, 0x00000823UL, 0x00000000UL,
    0x00000820UL, 0x00240000UL, 0x000009bcUL, 0x00000000UL,
    0x00000bc0UL, 0x00001000UL, 0x00000bc1UL, 0x00011000UL,
    0x00000bc2UL, 0x00001000UL, 0x00000bc3UL, 0x00011000UL,
    0x000009b0UL, 0x00000000UL, 0x00000711UL, 0x003f003fUL,
    0xc00f3500UL, 0x00030074UL, 0x40800000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x41e00000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x40800000UL, 0x41e00000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x0000070cUL, 0x00000000UL, 0x0000070eUL,
    0x00001000UL, 0x00000714UL, 0x00000002UL, 0x0000070fUL,
    0x00001902UL, 0x0000070bUL, 0x42227072UL, 0x0000075fUL,
    0x00000000UL, 0x00000761UL, 0xffffffffUL, 0x00000713UL,
    0x480055deUL, 0x0000082cUL, 0x00000300UL, 0x00000822UL,
    0x00000803UL, 0x00000823UL, 0x00000000UL, 0x00000820UL,
    0x00240000UL, 0x000009bcUL, 0x00000000UL, 0x00000bc0UL,
    0x00001000UL, 0x00000bc1UL, 0x00011000UL, 0x00000bc2UL,
    0x00001000UL, 0x00000bc3UL, 0x00011000UL, 0x000009b0UL,
    0x00000000UL, 0x00000711UL, 0x003f003fUL, 0xc00f3500UL,
    0x00030074UL, 0x40800000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x41e00000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x40800000UL,
    0x41e00000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0xc0012800UL, 0x00000000UL, 0x00000000UL, 0x0000070eUL,
    0x00001000UL, 0x00000714UL, 0x00000002UL, 0x0000070fUL,
    0x00001902UL, 0x0000070bUL, 0x42227072UL, 0x0000075fUL,
    0x00000000UL, 0x00000761UL, 0xffffffffUL, 0x00000713UL,
    0x480055deUL, 0x0000082cUL, 0x00000300UL, 0x00000822UL,
    0x00000803UL, 0x00000823UL, 0x00000000UL, 0x00000820UL,
    0x00240000UL, 0x000009bcUL, 0x00000000UL, 0x00000bc0UL,
    0x00001000UL, 0x00000bc1UL, 0x00011000UL, 0x00000bc2UL,
    0x00001000UL, 0x00000bc3UL, 0x00011000UL, 0x000009b0UL,
    0x00000000UL, 0x00000711UL, 0x003f003fUL, 0xc00f3500UL,
    0x00030074UL, 0x40800000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x41e00000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x40800000UL,
    0x41e00000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x00000822UL, 0x00000803UL, 0xc00e3500UL, 0x00030034UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000822UL, 0x00000803UL,
    0x00000711UL, 0x003f003fUL, 0x00000710UL, 0x00fff000UL,
    0x00000712UL, 0x00000040UL, 0xc00f3500UL, 0x00030034UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x0000070eUL,
    0x00001000UL, 0x00000714UL, 0x00000002UL, 0x0000070fUL,
    0x00001902UL, 0x0000070bUL, 0x42227072UL, 0x0000075fUL,
    0x00000000UL, 0x00000761UL, 0xffffffffUL, 0x00000713UL,
    0x480055deUL, 0x0000082cUL, 0x00000300UL, 0x00000822UL,
    0x00000803UL, 0x00000823UL, 0x00000000UL, 0x00000820UL,
    0x00240000UL, 0x000009bcUL, 0x00000000UL, 0x00000bc0UL,
    0x00001000UL, 0x00000bc1UL, 0x00011000UL, 0x00000bc2UL,
    0x00001000UL, 0x00000bc3UL, 0x00011000UL, 0x000009b0UL,
    0x00000000UL, 0x00000711UL, 0x003f003fUL, 0xc00f3500UL,
    0x00030074UL, 0x40800000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x41e00000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x40800000UL,
    0x41e00000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x00000712UL, 0x0003070bUL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x0000070eUL, 0x00001000UL, 0x00000714UL,
    0x00000002UL, 0x0000070fUL, 0x00001902UL, 0x0000070bUL,
    0x42227072UL, 0x0000075fUL, 0x00000000UL, 0x00000761UL,
    0xffffffffUL, 0x00000713UL, 0x480055deUL, 0x0000082cUL,
    0x00000300UL, 0x00000822UL, 0x00000803UL, 0x00000823UL,
    0x00000000UL, 0x00000820UL, 0x00240000UL, 0x000009bcUL,
    0x00000000UL, 0x00000bc0UL, 0x00001000UL, 0x00000bc1UL,
    0x00011000UL, 0x00000bc2UL, 0x00001000UL, 0x00000bc3UL,
    0x00011000UL, 0x000009b0UL, 0x00000000UL, 0x00000711UL,
    0x003f003fUL, 0xc00f3500UL, 0x00030074UL, 0x40800000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x41e00000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x40800000UL, 0x41e00000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x40000123UL, 0x0000070eUL,
    0x00001000UL, 0x00000714UL, 0x00000002UL, 0x0000070fUL,
    0x00001902UL, 0x0000070bUL, 0x42227072UL, 0x0000075fUL,
    0x00000000UL, 0x00000761UL, 0xffffffffUL, 0x00000713UL,
    0x480055deUL, 0x0000082cUL, 0x00000300UL, 0x00000822UL,
    0x00000803UL, 0x00000823UL, 0x00000000UL, 0x00000820UL,
    0x00240000UL, 0x000009bcUL, 0x00000000UL, 0x00000bc0UL,
    0x00001000UL, 0x00000bc1UL, 0x00011000UL, 0x00000bc2UL,
    0x00001000UL, 0x00000bc3UL, 0x00011000UL, 0x000009b0UL,
    0x00000000UL, 0x00000711UL, 0x003f003fUL, 0xc00f3500UL,
    0x00030074UL, 0x40800000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x41e00000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x40800000UL,
    0x41e00000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x80000000UL, 0x0000070eUL, 0x00001000UL, 0x00000714UL,
    0x00000002UL, 0x0000070fUL, 0x00001902UL, 0x0000070bUL,
    0x42227072UL, 0x0000075fUL, 0x00000000UL, 0x00000761UL,
    0xffffffffUL, 0x00000713UL, 0x480055deUL, 0x0000082cUL,
    0x00000300UL, 0x00000822UL, 0x00000803UL, 0x00000823UL,
    0x00000000UL, 0x00000820UL, 0x00240000UL, 0x000009bcUL,
    0x00000000UL, 0x00000bc0UL, 0x00001000UL, 0x00000bc1UL,
    0x00011000UL, 0x00000bc2UL, 0x00001000UL, 0x00000bc3UL,
    0x00011000UL, 0x000009b0UL, 0x00000000UL, 0x00000711UL,
    0x003f003fUL, 0xc00f3500UL, 0x00030074UL, 0x40800000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x41e00000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x40800000UL, 0x41e00000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0xc00f3500UL, 0x00030034UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000822UL,
    0x00000803UL, 0xc00f3500UL, 0x00030004UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000822UL, 0x00000803UL,
    0x00000711UL, 0x003f003fUL, 0x00000710UL, 0x00ff0000UL,
    0x00000712UL, 0x00001ff8UL, 0xc00f3500UL, 0x00030034UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000b00UL,
    0x00000010UL, 0x0000070eUL, 0x00001000UL, 0x00000714UL,
    0x00000002UL, 0x0000070fUL, 0x00001902UL, 0x0000070bUL,
    0x42227072UL, 0x0000075fUL, 0x00000000UL, 0x00000761UL,
    0xffffffffUL, 0x00000713UL, 0x480055deUL, 0x0000082cUL,
    0x00000300UL, 0x00000822UL, 0x00000803UL, 0x00000823UL,
    0x00000000UL, 0x00000820UL, 0x00240000UL, 0x000009bcUL,
    0x00000000UL, 0x00000bc0UL, 0x00001000UL, 0x00000bc1UL,
    0x00011000UL, 0x00000bc2UL, 0x00001000UL, 0x00000bc3UL,
    0x00011000UL, 0x000009b0UL, 0x00000000UL, 0x00000711UL,
    0x003f003fUL, 0xc00f3500UL, 0x00030074UL, 0x40800000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x41e00000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x40800000UL, 0x41e00000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x0000070eUL, 0x00000020UL,
    0x0000070eUL, 0x00001000UL, 0x00000714UL, 0x00000002UL,
    0x0000070fUL, 0x00001902UL, 0x0000070bUL, 0x42227072UL,
    0x0000075fUL, 0x00000000UL, 0x00000761UL, 0xffffffffUL,
    0x00000713UL, 0x480055deUL, 0x0000082cUL, 0x00000300UL,
    0x00000822UL, 0x00000803UL, 0x00000823UL, 0x00000000UL,
    0x00000820UL, 0x00240000UL, 0x000009bcUL, 0x00000000UL,
    0x00000bc0UL, 0x00001000UL, 0x00000bc1UL, 0x00011000UL,
    0x00000bc2UL, 0x00001000UL, 0x00000bc3UL, 0x00011000UL,
    0x000009b0UL, 0x00000000UL, 0x00000711UL, 0x003f003fUL,
    0xc00f3500UL, 0x00030074UL, 0x40800000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x41e00000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x40800000UL, 0x41e00000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x00000820UL, 0x00000001UL, 0x0000070eUL,
    0x00001000UL, 0x00000714UL, 0x00000002UL, 0x0000070fUL,
    0x00001902UL, 0x0000070bUL, 0x42227072UL, 0x0000075fUL,
    0x00000000UL, 0x00000761UL, 0xffffffffUL, 0x00000713UL,
    0x480055deUL, 0x0000082cUL, 0x00000300UL, 0x00000822UL,
    0x00000803UL, 0x00000823UL, 0x00000000UL, 0x00000820UL,
    0x00240000UL, 0x000009bcUL, 0x00000000UL, 0x00000bc0UL,
    0x00001000UL, 0x00000bc1UL, 0x00011000UL, 0x00000bc2UL,
    0x00001000UL, 0x00000bc3UL, 0x00011000UL, 0x000009b0UL,
    0x00000000UL, 0x00000711UL, 0x003f003fUL, 0xc00f3500UL,
    0x00030074UL, 0x40800000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x41e00000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x40800000UL,
    0x41e00000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x00000822UL, 0x00000803UL, 0x00000822UL, 0x00000040UL,
    0xc00f3500UL, 0x00030034UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000822UL, 0x00000803UL, 0xc00f3500UL,
    0x00030034UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000822UL, 0x00000803UL, 0x00000711UL, 0xffff003fUL,
    0xc00f3500UL, 0x00030034UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000822UL, 0x00000803UL, 0x00000711UL,
    0x003f0040UL, 0xc00f3500UL, 0x00030034UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000822UL, 0x00000803UL,
    0x00000711UL, 0x000f000fUL, 0x0000070aUL, 0x00000030UL,
    0xc00f3500UL, 0x00030034UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000822UL, 0x00000803UL, 0x00000711UL,
    0x0000003fUL, 0x00000709UL, 0x00fff800UL, 0xc00f3500UL,
    0x00030034UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000712UL, 0x00010040UL, 0x0000070eUL, 0x00001000UL,
    0x00000714UL, 0x00000002UL, 0x0000070fUL, 0x00001902UL,
    0x0000070bUL, 0x42227072UL, 0x0000075fUL, 0x00000000UL,
    0x00000761UL, 0xffffffffUL, 0x00000713UL, 0x480055deUL,
    0x0000082cUL, 0x00000300UL, 0x00000822UL, 0x00000803UL,
    0x00000823UL, 0x00000000UL, 0x00000820UL, 0x00240000UL,
    0x000009bcUL, 0x00000000UL, 0x00000bc0UL, 0x00001000UL,
    0x00000bc1UL, 0x00011000UL, 0x00000bc2UL, 0x00001000UL,
    0x00000bc3UL, 0x00011000UL, 0x000009b0UL, 0x00000000UL,
    0x00000711UL, 0x003f003fUL, 0xc00f3500UL, 0x00030074UL,
    0x40800000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x41e00000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x40800000UL, 0x41e00000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x0000070fUL,
    0x00000200UL, 0x0000070eUL, 0x00001000UL, 0x00000714UL,
    0x00000002UL, 0x0000070fUL, 0x00001902UL, 0x0000070bUL,
    0x42227072UL, 0x0000075fUL, 0x00000000UL, 0x00000761UL,
    0xffffffffUL, 0x00000713UL, 0x480055deUL, 0x0000082cUL,
    0x00000300UL, 0x00000822UL, 0x00000803UL, 0x00000823UL,
    0x00000000UL, 0x00000820UL, 0x00240000UL, 0x000009bcUL,
    0x00000000UL, 0x00000bc0UL, 0x00001000UL, 0x00000bc1UL,
    0x00011000UL, 0x00000bc2UL, 0x00001000UL, 0x00000bc3UL,
    0x00011000UL, 0x000009b0UL, 0x00000000UL, 0x00000711UL,
    0x003f003fUL, 0xc00f3500UL, 0x00030074UL, 0x40800000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x41e00000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x40800000UL, 0x41e00000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x00000758UL, 0x00000001UL,
    0x0000070eUL, 0x00001000UL, 0x00000714UL, 0x00000002UL,
    0x0000070fUL, 0x00001902UL, 0x0000070bUL, 0x42227072UL,
    0x0000075fUL, 0x00000000UL, 0x00000761UL, 0xffffffffUL,
    0x00000713UL, 0x480055deUL, 0x0000082cUL, 0x00000300UL,
    0x00000822UL, 0x00000803UL, 0x00000823UL, 0x00000000UL,
    0x00000820UL, 0x00240000UL, 0x000009bcUL, 0x00000000UL,
    0x00000bc0UL, 0x00001000UL, 0x00000bc1UL, 0x00011000UL,
    0x00000bc2UL, 0x00001000UL, 0x00000bc3UL, 0x00011000UL,
    0x000009b0UL, 0x00000000UL, 0x00000711UL, 0x003f003fUL,
    0xc00f3500UL, 0x00030074UL, 0x40800000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x41e00000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x40800000UL, 0x41e00000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x00000822UL, 0x00000803UL, 0x00000711UL,
    0x003f003fUL, 0x00000b40UL, 0x00000000UL, 0xc00f3500UL,
    0x00030034UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000822UL, 0x00000803UL, 0x00000711UL, 0x003f003fUL,
    0x00000b01UL, 0x00009906UL, 0x00000b00UL, 0x00000000UL,
    0x00000b40UL, 0x00f00020UL, 0xc00f3500UL, 0x00030034UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000b01UL,
    0x00009906UL, 0x00000b00UL, 0x00000000UL, 0x00000b40UL,
    0x00f00000UL, 0x0000070eUL, 0x00001000UL, 0x00000714UL,
    0x00000002UL, 0x0000070fUL, 0x00001902UL, 0x0000070bUL,
    0x42227072UL, 0x0000075fUL, 0x00000000UL, 0x00000761UL,
    0xffffffffUL, 0x00000713UL, 0x480055deUL, 0x0000082cUL,
    0x00000300UL, 0x00000822UL, 0x00000803UL, 0x00000823UL,
    0x00000000UL, 0x00000820UL, 0x00240000UL, 0x000009bcUL,
    0x00000000UL, 0x00000bc0UL, 0x00001000UL, 0x00000bc1UL,
    0x00011000UL, 0x00000bc2UL, 0x00001000UL, 0x00000bc3UL,
    0x00011000UL, 0x000009b0UL, 0x00000000UL, 0x00000711UL,
    0x003f003fUL, 0xc00f3500UL, 0x00030074UL, 0x40800000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x41e00000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x40800000UL, 0x41e00000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x00000822UL, 0x00000803UL,
    0x00000711UL, 0x003f003fUL, 0x00000b01UL, 0x00009906UL,
    0x00000b00UL, 0x00000000UL, 0x00000b40UL, 0x00000010UL,
    0xc00f3500UL, 0x00030034UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000822UL, 0x00000803UL, 0x00000711UL,
    0x003f003fUL, 0x00000b01UL, 0x00009906UL, 0x00000b00UL,
    0x00000000UL, 0x00000b40UL, 0x00000008UL, 0xc00f3500UL,
    0x00030034UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000b01UL, 0x00003303UL, 0x0000070eUL, 0x00001000UL,
    0x00000714UL, 0x00000002UL, 0x0000070fUL, 0x00001902UL,
    0x0000070bUL, 0x42227072UL, 0x0000075fUL, 0x00000000UL,
    0x00000761UL, 0xffffffffUL, 0x00000713UL, 0x480055deUL,
    0x0000082cUL, 0x00000300UL, 0x00000822UL, 0x00000803UL,
    0x00000823UL, 0x00000000UL, 0x00000820UL, 0x00240000UL,
    0x000009bcUL, 0x00000000UL, 0x00000bc0UL, 0x00001000UL,
    0x00000bc1UL, 0x00011000UL, 0x00000bc2UL, 0x00001000UL,
    0x00000bc3UL, 0x00011000UL, 0x000009b0UL, 0x00000000UL,
    0x00000711UL, 0x003f003fUL, 0xc00f3500UL, 0x00030074UL,
    0x40800000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x41e00000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x40800000UL, 0x41e00000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x00000705UL,
    0x00000800UL, 0x0000070eUL, 0x00001000UL, 0x00000714UL,
    0x00000002UL, 0x0000070fUL, 0x00001902UL, 0x0000070bUL,
    0x42227072UL, 0x0000075fUL, 0x00000000UL, 0x00000761UL,
    0xffffffffUL, 0x00000713UL, 0x480055deUL, 0x0000082cUL,
    0x00000300UL, 0x00000822UL, 0x00000803UL, 0x00000823UL,
    0x00000000UL, 0x00000820UL, 0x00240000UL, 0x000009bcUL,
    0x00000000UL, 0x00000bc0UL, 0x00001000UL, 0x00000bc1UL,
    0x00011000UL, 0x00000bc2UL, 0x00001000UL, 0x00000bc3UL,
    0x00011000UL, 0x000009b0UL, 0x00000000UL, 0x00000711UL,
    0x003f003fUL, 0xc00f3500UL, 0x00030074UL, 0x40800000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x41e00000UL, 0x40800000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x40800000UL, 0x41e00000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x00000705UL, 0x000005aaUL,
    0x0000070eUL, 0x00001000UL, 0x00000714UL, 0x00000002UL,
    0x0000070fUL, 0x00001902UL, 0x0000070bUL, 0x42227072UL,
    0x0000075fUL, 0x00000000UL, 0x00000761UL, 0xffffffffUL,
    0x00000713UL, 0x480055deUL, 0x0000082cUL, 0x00000300UL,
    0x00000822UL, 0x00000803UL, 0x00000823UL, 0x00000000UL,
    0x00000820UL, 0x00240000UL, 0x000009bcUL, 0x00000000UL,
    0x00000bc0UL, 0x00001000UL, 0x00000bc1UL, 0x00011000UL,
    0x00000bc2UL, 0x00001000UL, 0x00000bc3UL, 0x00011000UL,
    0x000009b0UL, 0x00000000UL, 0x00000711UL, 0x003f003fUL,
    0xc00f3500UL, 0x00030074UL, 0x40800000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x41e00000UL,
    0x40800000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL,
    0x40800000UL, 0x41e00000UL, 0x3f800000UL, 0x3f800000UL,
    0x78563412UL, 0x00000822UL, 0x00000803UL, 0x00000711UL,
    0x003f003fUL, 0x00000710UL, 0x00fff000UL, 0x00000712UL,
    0x00000040UL, 0xc00f3500UL, 0x00030034UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000710UL, 0x00000000UL,
    0xc00f3500UL, 0x00030034UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000822UL, 0x00000803UL, 0x00000711UL,
    0x003f003fUL, 0x00000b01UL, 0x00009906UL, 0x00000b00UL,
    0x00000000UL, 0x00000b40UL, 0x00ffffe0UL, 0xc00f3500UL,
    0x00030034UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000b01UL, 0x00009906UL, 0x00000b00UL, 0x00000000UL,
    0x00000b40UL, 0x00000000UL, 0xc00f3500UL, 0x00030034UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000822UL,
    0x00000803UL, 0x00000711UL, 0x003f003fUL, 0x00000b01UL,
    0x00006606UL, 0x00000b00UL, 0x00030004UL, 0x00000b40UL,
    0x00000000UL, 0xc00f3500UL, 0x00030034UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000822UL, 0x00000803UL,
    0x00000711UL, 0x003f003fUL, 0x00000b01UL, 0x00006606UL,
    0x00000b00UL, 0x00070004UL, 0x00000b40UL, 0x00000000UL,
    0xc00f3500UL, 0x00030034UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL,
    0x00000000UL, 0x00000b00UL, 0x00100000UL, 0x0000070eUL,
    0x00001000UL, 0x00000714UL, 0x00000002UL, 0x0000070fUL,
    0x00001902UL, 0x0000070bUL, 0x42227072UL, 0x0000075fUL,
    0x00000000UL, 0x00000761UL, 0xffffffffUL, 0x00000713UL,
    0x480055deUL, 0x0000082cUL, 0x00000300UL, 0x00000822UL,
    0x00000803UL, 0x00000823UL, 0x00000000UL, 0x00000820UL,
    0x00240000UL, 0x000009bcUL, 0x00000000UL, 0x00000bc0UL,
    0x00001000UL, 0x00000bc1UL, 0x00011000UL, 0x00000bc2UL,
    0x00001000UL, 0x00000bc3UL, 0x00011000UL, 0x000009b0UL,
    0x00000000UL, 0x00000711UL, 0x003f003fUL, 0xc00f3500UL,
    0x00030074UL, 0x40800000UL, 0x40800000UL, 0x3f800000UL,
    0x3f800000UL, 0x78563412UL, 0x41e00000UL, 0x40800000UL,
    0x3f800000UL, 0x3f800000UL, 0x78563412UL, 0x40800000UL,
    0x41e00000UL, 0x3f800000UL, 0x3f800000UL, 0x78563412UL
};
static const unsigned short cpR7Cases[37][3] = {   /* first, count, why */
    {     0,   53,  0 },   /* U1 */
    {    53,   55,  4 },   /* U3 */
    {   108,   56,  6 },   /* U4 */
    {   164,   18, 10 },   /* U5 */
    {   182,   25, 11 },   /* U6 */
    {   207,   54,  2 },   /* U7 */
    {   261,   57,  3 },   /* U9 */
    {   318,   54,  1 },   /* U10 */
    {   372,   54,  1 },   /* U10b */
    {   426,   17,  9 },   /* U11 */
    {   443,   19,  7 },   /* U12 */
    {   462,   25, 11 },   /* U13 */
    {   487,   55,  5 },   /* U14 */
    {   542,   55,  5 },   /* U14b */
    {   597,   55,  5 },   /* U14c */
    {   652,   21,  8 },   /* U16 */
    {   673,   19, 11 },   /* U17 */
    {   692,   21, 11 },   /* U18 */
    {   713,   21, 11 },   /* U19 */
    {   734,   23, 11 },   /* U20 */
    {   757,   23, 11 },   /* U21 */
    {   780,   55,  5 },   /* U22 */
    {   835,   55,  5 },   /* U23 */
    {   890,   55,  5 },   /* U24 */
    {   945,   23, 11 },   /* U25 */
    {   968,   27, 11 },   /* U26 */
    {   995,   59,  0 },   /* U27 */
    {  1054,   27, 11 },   /* U28 */
    {  1081,   27, 11 },   /* U29 */
    {  1108,   55,  5 },   /* U30 */
    {  1163,   55,  5 },   /* U31 */
    {  1218,   55,  0 },   /* U32 */
    {  1273,   44, 11 },   /* U34 */
    {  1317,   50, 11 },   /* U35 */
    {  1367,   27,  0 },   /* U36 */
    {  1394,   27, 11 },   /* U37 */
    {  1421,   55,  5 },   /* U38 */
};
/* 1 where the word is a surface address: the consumer adds its own winStart, so no
   boot's address is baked into this table. */
static const unsigned char cpR7Fix[1476] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0
};
/* <<<END GENERATED CASES>>> */

static int
usage(void)
{
    printf("RDNR7B usage: rdnr7dev <runid> <major> <case> [n=<count>] [unknown] [hold]\n");
    return 2;
}

int
main(int argc, char **argv)
{
    osrdn_r7b_caps caps;
    osrdn_r7b_submit sub;
    unsigned long *page;
    vm_address_t addr = 0;
    unsigned long which, maj, n, first, fixup, i, over = 0UL;
    int unknownCmd = 0, holdTest = 0, fd2;
    const char *runid;
    char *end;
    struct stat st;
    int fd, a;

    if (argc < 4)
        return usage();
    runid = argv[1];
    maj = strtoul(argv[2], &end, 0);
    if (*end != '\0' || maj == 0UL || maj > 255UL)
        return usage();
    which = strtoul(argv[3], &end, 0);
    if (*end != '\0' || which >= (unsigned long)CP_R7_CASE_COUNT)
        return usage();
    for (a = 4; a < argc; a++) {
        if (strncmp(argv[a], "n=", 2) == 0) {
            over = strtoul(argv[a] + 2, &end, 0) + 1UL;  /* +1: 0 is "not given" */
            if (*end != '\0')
                return usage();
        } else if (strcmp(argv[a], "unknown") == 0) {
            unknownCmd = 1;
        } else if (strcmp(argv[a], "hold") == 0) {
            holdTest = 1;
        } else {
            return usage();
        }
    }

    /* the node: the driver pins its major, so a pure-C client needs no lookup.
       A node left by an earlier run may point at a major this driver no longer
       has, so an existing one is checked rather than trusted. */
    if (stat(NODE, &st) == 0) {
        if (!IS_CHR(st.st_mode) || (unsigned long)major(st.st_rdev) != maj) {
            printf("RDNR7B run=%s step=node mode=%o rdev=%04x want-major=%lu\n",
                   runid, (unsigned)st.st_mode, (unsigned)st.st_rdev, maj);
            return 3;
        }
    } else if (mknod(NODE, S_IFCHR | 0600, (int)((maj << 8) | 0UL)) != 0) {
        printf("RDNR7B run=%s step=mknod errno=%d\n", runid, errno);
        return 3;
    }
    if ((fd = open(NODE, O_RDWR)) < 0) {
        printf("RDNR7B run=%s step=open errno=%d\n", runid, errno);
        return 3;
    }

    memset((char *)&caps, 0, sizeof caps);
    if (ioctl(fd, (int)OSRDN_R7B_IOC_CAPS, (char *)&caps) != 0) {
        printf("RDNR7B run=%s step=caps errno=%d\n", runid, errno);
        (void)close(fd);
        return 4;
    }
    printf("RDNR7B run=%s step=caps magic=%08lx ver=%lu win=%08lx bytes=%lu max=%lu "
           "build=%08lx ready=%lu cprunning=%lu winstart=%08lx\n",
           runid, caps.magic, caps.version, caps.window, caps.bytes, caps.maxWords,
           caps.build, caps.ready, caps.cpRunning, caps.winStart);
    if (caps.magic != OSRDN_R7B_MAGIC || caps.version != OSRDN_R7B_VERSION ||
        caps.window != OSRDN_R7B_WINDOW_OFF || caps.bytes != OSRDN_R7B_WINDOW_BYTES ||
        caps.maxWords != OSRDN_R7B_MAX_WORDS || caps.ready != 1UL) {
        printf("RDNR7B run=%s step=caps refused\n", runid);
        (void)close(fd);
        return 4;
    }

    /* gate C: a second open while this one holds the node.  It must be refused,
       and it must change nothing -- which is what every run AFTER this one shows,
       so this mode stops here rather than submitting. */
    if (holdTest) {
        fd2 = open(NODE, O_RDWR);
        printf("RDNR7B run=%s step=hold second-open=%d errno=%d\n", runid, fd2, errno);
        if (fd2 >= 0) {
            printf("RDNR7B run=%s step=hold THE SECOND OPEN WAS ALLOWED\n", runid);
            (void)close(fd2);
            (void)close(fd);
            return 6;
        }
        (void)close(fd);
        return 0;
    }

    /* gate E: a command in this group the driver does not answer.  It must be
       refused, and the driver must leave the number in the log. */
    if (unknownCmd) {
        unsigned long bogus = OSRDN_R7B_IOC_OUT |
            ((sizeof(osrdn_r7b_caps) & OSRDN_R7B_IOC_PARM_MASK) << 16) |
            ((unsigned long)OSRDN_R7B_IOC_GROUP << 8) | 9UL;
        int rc = ioctl(fd, (int)bogus, (char *)&caps);

        printf("RDNR7B run=%s step=unknown cmd=%08lx rc=%d errno=%d\n", runid, bogus, rc, errno);
        (void)close(fd);
        return rc == 0 ? 6 : 0;         /* answering it would be the failure */
    }

    /* the window: allocate the place, then map over it */
    if (vm_allocate(task_self(), &addr, (vm_size_t)caps.bytes, TRUE) != KERN_SUCCESS) {
        printf("RDNR7B run=%s step=vmalloc errno=%d\n", runid, errno);
        (void)close(fd);
        return 5;
    }
    if ((int)mmap((caddr_t)addr, (int)caps.bytes, PROT_RW, MAP_SHARED_, fd,
                  (off_t)caps.window) == -1) {
        printf("RDNR7B run=%s step=mmap errno=%d\n", runid, errno);
        (void)close(fd);
        return 5;
    }
    page = (unsigned long *)addr;

    first = (unsigned long)cpR7Cases[which][0];
    n = (unsigned long)cpR7Cases[which][1];
    for (i = 0UL; i < n; i++) {
        fixup = cpR7Fix[first + i] ? caps.winStart : 0UL;
        page[i] = cpR7Pool[first + i] + fixup;
    }
    printf("RDNR7B run=%s step=fill case=%lu n=%lu want=%u\n",
           runid, which, n, (unsigned)cpR7Cases[which][2]);

    memset((char *)&sub, 0, sizeof sub);
    sub.magic = OSRDN_R7B_MAGIC;
    sub.version = OSRDN_R7B_VERSION;
    sub.nwords = over ? over - 1UL : n;
    /* the seed: the run id, as R7a's tool does.  It must be non-zero and must not
       repeat, and a new run id per call is what gives both. */
    sub.seed = strtoul(runid, &end, 10);
    if (ioctl(fd, (int)OSRDN_R7B_IOC_SUBMIT, (char *)&sub) != 0) {
        printf("RDNR7B run=%s step=submit errno=%d\n", runid, errno);
        (void)close(fd);
        return 6;
    }
    printf("RDNR7B run=%s step=submit n=%lu seed=%lu status=%lu why=%lu at=%lu word=%08lx "
           "drawn=%lu\n",
           runid, sub.nwords, sub.seed, sub.status, sub.why, sub.at, sub.word, sub.drawn);
    (void)close(fd);
    return 0;
}
