/*
 * OSRDNMesaVerify.c - the kernel's stream verifier, in the library (G4-2 B0,
 * docs/G4_2_BATCH_PLAN.md 2).  GENERATED by tools/mesa/gen_r7verify.py from the kernel's
 * osrdn_cp.m: the functions below are that file's text with the kernel state type renamed to the
 * four fields they use.  Do not edit; regenerate (check-all refuses a stale copy).
 */
#include "OSRDNMesaVerify.h"

typedef struct {
    unsigned long r7WinStart, r7WinEnd;     /* the window, read */
    unsigned long r7At, r7Word;             /* where a refusal stopped, written */
} osrdn_r7v;

/* the register addresses the kernel names (osrdn_cp.m) */
#define C_PP_CNTL               0x1c38
#define C_PP_TXFILTER_0         0x2c00
#define C_PP_TXFORMAT_0         0x2c04
#define C_PP_TXOFFSET_0         0x2d00
#define C_RB3D_CNTL             0x1c3c
#define C_RB3D_COLOROFFSET      0x1c40
#define C_RB3D_COLORPITCH       0x1c48
#define C_RB3D_DEPTHOFFSET      0x1c24
#define C_RB3D_DEPTHPITCH       0x1c28
#define C_RB3D_DEPTHXY_OFFSET   0x1d60
#define C_RE_WIDTH_HEIGHT       0x1c44
#define C_SE_VAP_CNTL           0x2080
#define C_SE_VTX_FMT_0          0x2088
#define C_SE_VTX_FMT_1          0x208c

/* R7a (docs/R7_PLAN.md 4): the value masks, the vertex format's measured fields, and VF_CNTL.
   Every one of these names a field this project HAS measured; anything else is refused. */
#define CP_R7_PP_CNTL_TEX_1_5   0x000003e0UL    /* R200_TEX_1..5_ENABLE (r200_reg.h 157-176) */
#define CP_R7_VAP_TCL           0x00000001UL
#define CP_R7_TXFORMAT_CUBIC    0x08000000UL
/* G4-4 K5 (docs/G4_4_KERNEL_PLAN.md 4-1): PP_TXFILTER's fields this project has NOT measured, refused
   as a value rule -- the anisotropic MIN modes (r200_reg.h 835-838: 8..11 << 1, all carry bit 4), the
   bits the header does not name (8-15), and YUV (r200_reg.h 848-851: bits 20-21).  The mip MIN modes
   (bit 2, r200_reg.h 831-834) and MAX_MIP_LEVEL [19:16] are allowed: cpR7TextureBytes sizes the chain
   they name.  The mask this replaces, 0x1c000, was bits 14-16 -- neither the MIN field nor the whole
   level field (build/g44/model.py). */
#define CP_R7_TXFILTER_UNMEASURED 0x0030ff10UL
/* G4-3 K3 (docs/G4_3_KERNEL_PLAN.md 4): the words the card reads a texture's footprint from --
   Mesa-6.5.3 r200_reg.h 882/897 (FORMAT field, ARGB8888 = 6), 902-905 (log2 width at bit 8, log2
   height at bit 12), 846-847 (MAX_MIP_LEVEL at bit 16), 1071-1076 (the TXOFFSET low bits are endian
   swaps and tiling).  The oracle (tools/r7/verify_oracle.py) carries the same numbers. */
#define CP_R7_TXFORMAT_FMT_MASK 0x0000001fUL
#define CP_R7_TXFORMAT_ARGB8888 0x00000006UL
#define CP_R7_TXFORMAT_W_SHIFT  8
#define CP_R7_TXFORMAT_H_SHIFT  12
#define CP_R7_TXFORMAT_LOG2_MAX 11UL            /* 2048: the R200's largest side */
#define CP_R7_TXFILTER_MIP_SHIFT 16
#define CP_R7_TXO_LOW_MASK      0x0000001fUL    /* endian, macro/micro tile, and the 32-byte grain R6h measured */
/* G4-3 K2 (docs/G4_3_KERNEL_PLAN.md 3): the alpha test's reference byte [7:0] and compare [10:8]
   (r200_reg.h 33-43); the enable is PP_CNTL bit 23, already inside that register's rule */
#define C_PP_MISC               0x1c14
#define CP_R7_PP_MISC_FIELDS    0x000007ffUL
#define CP_R7_VTX0_ALLOWED      0x00001803UL    /* Z0 | W0 | the COLOR_0 field */
#define CP_R7_VF_PRIM_MASK      0x0000000fUL
#define CP_R7_VF_PRIM_TRIANGLES 0x00000004UL
#define CP_R7_VF_WALK_MASK      0x00000030UL
#define CP_R7_VF_WALK_RING      0x00000030UL
#define CP_R7_VF_ALLOWED        0xffff007fUL    /* prim, walk, COLOR_ORDER_RGBA, the vertex count */
#define CP_R7_PITCH_MASK        0x00001ff8UL    /* R200_COLORPITCH_MASK: the pitch is in pixels */
#define CP_R7_RB3D_XY_OFFSET    0x00000200UL    /* M3h: R200_DEPTH_XZ_OFFEST_ENABLE (Mesa-6.5.3 r200_reg.h 195) */
#define CP_R7_PREFIX_FMT0       0x00000003UL    /* what the R7 prefix leaves: Z0 | W0 */
#define CP_R7_PREFIX_FMT1       0x00000000UL

/* R7a (docs/R7_PLAN.md 4): the registers a client may write -- the 49 the R6 ladder
   measured, less the 7 the driver keeps for itself.  GENERATED by
   tools/r7/verify_oracle.py --c-tables; check_r7_src.py compares the two. */
static const unsigned short cpR7Allow[42] = {
    0x1c14, 0x1c20, 0x1c24, 0x1c28, 0x1c2c, 0x1c38, 0x1c3c, 0x1c40,
    0x1c44, 0x1c48, 0x1c4c, 0x1c50, 0x1cd8, 0x1cdc, 0x1ce0, 0x1ce4,
    0x1ce8, 0x1cec, 0x1d60, 0x1d7c, 0x1d84, 0x2080, 0x2088, 0x208c,
    0x20b0, 0x2140, 0x2180, 0x2284, 0x26c0, 0x26f0, 0x2c00, 0x2c04,
    0x2c08, 0x2c0c, 0x2c10, 0x2c1c, 0x2cc4, 0x2d00, 0x2f00, 0x2f04,
    0x2f08, 0x2f0c
};
#define CP_R7_ALLOW_COUNT        42

/* the 7 a client may NOT write, named so the reason is readable in review */
/*   0x15e0 SCRATCH_REG0 */
/*   0x1720 WAIT_UNTIL */
/*   0x2cf8 PP_TRI_PERF (G4-7) */
/*   0x2cfc PP_PERF_CNTL (G4-7) */
/*   0x2d9c PP_TAM_DEBUG3 (G4-9) */
/*   0x3254 RB3D_ZCACHE_CTLSTAT */
/*   0x325c RB3D_DSTCACHE_CTLSTAT */

/* R7a (docs/R7_PLAN.md 4): the client's staged stream, and the verifier that decides whether any
   of it may reach the ring.

   Nothing here touches the hardware.  It reads the staged words, and either returns 0 -- after
   which cpZclear copies them -- or a CP_R7_WHY_* saying which rule refused, with c->r7At holding
   the word it stopped at.  The whole stream is judged before one word is copied, so a refusal
   leaves the surfaces exactly as ZPREP left them (docs/R7_PLAN.md 2-1 C).

   The register allow-list is GENERATED from the registers the R6 ladder measured
   (tools/r7/verify_oracle.py --c-tables); check_r7_src.py compares the two, so a register nobody
   measured cannot become legal by being typed in here. */


static int
cpR7RegAllowed(unsigned long reg)
{
    unsigned long k;

    for (k = 0; k < (unsigned long)CP_R7_ALLOW_COUNT; k++)
        if ((unsigned long)cpR7Allow[k] == reg)
            return 1;
    return 0;
}

/* An allowed register is not an allowed VALUE.  These four values reach state the verifier cannot
   check: texture units whose offsets it never sees, an execution path nobody measured, and
   samplers that read past the area it did check (docs/R7_PLAN.md 4 rule 4). */
static int
cpR7ValueAllowed(unsigned long reg, unsigned long val)
{
    /*
     * M3h (docs/M3H_PLAN.md 3-4): the three ways an allowed register moves or widens what the card
     * writes past offset + pitch x rows.  A pitch word carrying anything but the pitch -- colour
     * tiling and microtiling, depth HyperZ, the endian fields -- and the depth XY offset with the
     * RB3D_CNTL bit that switches it on.  The footprint below is only true without them.
     */
    if ((reg == C_RB3D_COLORPITCH || reg == C_RB3D_DEPTHPITCH) && (val & ~CP_R7_PITCH_MASK) != 0UL)
        return 0;
    if (reg == C_RB3D_CNTL && (val & CP_R7_RB3D_XY_OFFSET) != 0UL)
        return 0;
    if (reg == C_RB3D_DEPTHXY_OFFSET && val != 0UL)
        return 0;
    if (reg == C_PP_CNTL && (val & CP_R7_PP_CNTL_TEX_1_5) != 0UL)
        return 0;                       /* units 1-5 would sample PP_TXOFFSET_1..5, never validated */
    if (reg == C_SE_VAP_CNTL && (val & CP_R7_VAP_TCL) != 0UL)
        return 0;                       /* TCL on: a path this project has never measured */
    if (reg == C_PP_TXFORMAT_0 && (val & CP_R7_TXFORMAT_CUBIC) != 0UL)
        return 0;                       /* a cube map reads five more faces */
    if (reg == C_PP_TXFILTER_0 && (val & CP_R7_TXFILTER_UNMEASURED) != 0UL)
        return 0;                       /* G4-4 K5: anisotropy, unnamed bits, YUV -- never measured */
    if (reg == C_PP_TXFORMAT_0 && (val & CP_R7_TXFORMAT_FMT_MASK) != CP_R7_TXFORMAT_ARGB8888)
        return 0;                       /* G4-3 K3: 4 bytes a texel is the only layout measured (R6h) */
    if (reg == C_PP_MISC && (val & ~CP_R7_PP_MISC_FIELDS) != 0UL)
        return 0;                       /* G4-3 K2: only the alpha reference and compare */
    return 1;
}

/*
 * G4-3 K3: the bytes a texture occupies, from the registers the card reads it with.  Level i of a
 * non-tiled 2D ARGB8888 texture is ((w >> i) * 4 rounded to 32) x (h >> i) bytes, each level starts
 * 32-byte aligned and the chain is contiguous from TXOFFSET (r200SetTexImages, r200_texstate.c
 * 271-278; no per-level offset register exists on the R200).  0 when the words describe something
 * this driver has not measured.
 */
static unsigned long
cpR7TextureBytes(unsigned long tfmt, unsigned long tfil)
{
    unsigned long lw = (tfmt >> CP_R7_TXFORMAT_W_SHIFT) & 15UL, lh = (tfmt >> CP_R7_TXFORMAT_H_SHIFT) & 15UL;
    unsigned long levels = ((tfil >> CP_R7_TXFILTER_MIP_SHIFT) & 15UL) + 1UL;
    unsigned long i, w, h, row, bytes = 0UL;

    if ((tfmt & CP_R7_TXFORMAT_FMT_MASK) != CP_R7_TXFORMAT_ARGB8888)
        return 0UL;
    if (lw > CP_R7_TXFORMAT_LOG2_MAX || lh > CP_R7_TXFORMAT_LOG2_MAX)
        return 0UL;
    if (levels > (lw > lh ? lw : lh) + 1UL)
        return 0UL;                     /* more levels than the base can halve into */
    for (i = 0UL; i < levels; i++) {
        w = (lw > i) ? (1UL << (lw - i)) : 1UL;
        h = (lh > i) ? (1UL << (lh - i)) : 1UL;
        row = (w * 4UL + 31UL) & ~31UL;
        bytes = ((bytes + 31UL) & ~31UL) + row * h;
    }
    return bytes;
}

/* the texture at toff, described by tfmt/tfil, lies inside the client's window */
static int
cpR7TextureFits(const osrdn_r7v *c, unsigned long toff, unsigned long tfmt, unsigned long tfil)
{
    unsigned long bytes = cpR7TextureBytes(tfmt, tfil);

    if (bytes == 0UL || (toff & CP_R7_TXO_LOW_MASK) != 0UL)
        return 0;
    if (toff < c->r7WinStart || toff > c->r7WinEnd)
        return 0;
    return (c->r7WinEnd - toff) >= bytes;
}

/* Words per vertex, from SE_VTX_FMT_0/1.  0 means "a field whose width this project has never
   measured" -- a normal, a weight count, a floating colour.  Guessing one wrong either refuses a
   legal stream or, worse, lets a short one through and the CP reads past the vertices
   (docs/R7_PLAN.md 4-1 b). */
static unsigned long
cpR7VertexWords(unsigned long fmt0, unsigned long fmt1)
{
    unsigned long n, unit, k, colour;

    if ((fmt0 & ~CP_R7_VTX0_ALLOWED) != 0UL)
        return 0UL;
    colour = (fmt0 >> 11) & 3UL;
    if (colour > 1UL)                   /* NOT_PRESENT or PK_RGBA; FP_RGB(A) unmeasured */
        return 0UL;
    n = 2UL;                            /* R200_VTX_XY: always there */
    if ((fmt0 & 1UL) != 0UL)
        n++;                            /* Z0 */
    if ((fmt0 & 2UL) != 0UL)
        n++;                            /* W0 */
    n += colour;
    for (unit = 0; unit < 6UL; unit++) {
        k = (fmt1 >> (3UL * unit)) & 7UL;
        if (k != 0UL && k != 2UL)       /* only two ST components have been measured */
            return 0UL;
        n += k;
    }
    if ((fmt1 >> 18) != 0UL)
        return 0UL;
    return n;
}

/* A surface's footprint, not its width and height: the pitch is the client's to set, so a small
   picture at a large pitch runs off the window from the second row on (docs/R7_PLAN.md 4 rule 7).

   M3h: THE ROWS ARE THE STREAM'S OWN CLIP, not 64.  The card draws rows 0 .. height of
   RE_WIDTH_HEIGHT and nothing below (the scissors only take away), and a width wider than the
   pitch would carry the last row on into the next -- so it is refused.  Four bytes a pixel is the
   widest colour format (ARGB8888) and covers 16- and 32-bit depth; depth is tiled, so its rows
   go up to the next 16 and its pitch must be whole 32-pixel tiles, as the reference allocates it
   (xf86 radeon_accel.c 1187-1189).  COLOROFFSET's low four bits are dropped by the card. */
static int
cpR7SurfaceFits(const osrdn_r7v *c, unsigned long off, unsigned long pitch,
                unsigned long rows, unsigned long cols, int depth)
{
    unsigned long p = pitch & CP_R7_PITCH_MASK, r = rows, span;

    off &= ~0xfUL;
    if (p == 0UL || cols > p || r == 0UL)
        return 0;
    if (depth) {
        if ((p & 31UL) != 0UL)
            return 0;
        r = (r + 15UL) & ~15UL;
    }
    if (p > 0xFFFFFFFFUL / 4UL / r)
        return 0;
    span = p * 4UL * r;
    if (off < c->r7WinStart || off > c->r7WinEnd)
        return 0;
    return (c->r7WinEnd - off) >= span;
}

/*
 * G4-4 K7 (docs/G4_4_KERNEL_PLAN.md 3): the surfaces a draw would touch, judged with the values
 * in force AT THAT DRAW.  Until K7 this ran once after the loop, on the last values, so a stream
 * that pointed a surface outside the window, drew, and pointed it back again passed (found by
 * the G4-2 plan's review).  It still runs after the loop as well: the last draw's judgement is
 * then made twice, and there is no way for the two to disagree.
 *
 * M3h: the clip must be the stream's own -- the card keeps the last one it was given, and that
 * may be another client's -- and it is read as the whole half-word, not the 11 bits a scissor
 * field was measured to use: a wider guess only makes the footprint larger.
 * G4-3 K3: a texture's footprint is what its format says it is, not a fixed 1 KiB (which let a
 * 512 x 512 image read a megabyte past the window unseen); a stream that points at texels
 * without stating their shape has no footprint to judge and is refused.
 */
static int
cpR7SurfacesOk(const osrdn_r7v *c, unsigned long coff, unsigned long cpitch,
               unsigned long zoff, unsigned long zpitch, unsigned long wh, int haveWH,
               unsigned long toff, unsigned long tfmt, unsigned long tfil, int haveT, int haveTF)
{
    if (!haveWH)
        return 0;
    if (!cpR7SurfaceFits(c, coff, cpitch, ((wh >> 16) & 0xffffUL) + 1UL, (wh & 0xffffUL) + 1UL, 0))
        return 0;
    if (!cpR7SurfaceFits(c, zoff, zpitch, ((wh >> 16) & 0xffffUL) + 1UL, (wh & 0xffffUL) + 1UL, 1))
        return 0;
    if (haveT && (!haveTF || !cpR7TextureFits(c, toff, tfmt, tfil)))
        return 0;
    return 1;
}

static unsigned long
cpR7Verify(osrdn_r7v *c, const unsigned long *w, unsigned long n,
           unsigned long defC, unsigned long defZ, unsigned long defPitch)
{
    unsigned long i, hdr, t, cnt, reg, val, vf, nv, vw;
    unsigned long fmt0, fmt1, coff, cpitch, zoff, zpitch, toff, wh, tfmt, tfil;
    int haveT, haveWH, drew, sawFmt, haveTF;

    c->r7At = 0UL;
    c->r7Word = 0UL;
    if (n == 0UL)
        return CP_R7_WHY_EMPTY;
    if (n > (unsigned long)CP_R7_BATCH_MAX)
        return CP_R7_WHY_WORDS;
    /* what the prefix leaves, so "the client never set the format" is still a defined state and
       never means "whatever the last client left" (docs/R7_PLAN.md 4-1 c) */
    fmt0 = CP_R7_PREFIX_FMT0;
    fmt1 = CP_R7_PREFIX_FMT1;
    /* M3h: and the surfaces the prefix points at -- the card draws into them unless the client
       moves them, so they are judged too rather than skipped */
    coff = defC; cpitch = defPitch; zoff = defZ; zpitch = defPitch; toff = 0UL; wh = 0UL;
    tfmt = 0UL; tfil = 0UL;
    haveT = 0; haveWH = 0; drew = 0; sawFmt = 0; haveTF = 0;
    i = 0UL;
    while (i < n) {
        c->r7At = i;
        hdr = w[i];
        c->r7Word = hdr;
        /* The packet type is the TOP TWO BITS and nothing else, so it is taken as a 0..3 number
           rather than compared against three 32-bit constants.  The first version did the latter
           and the target's cc disagreed with the host compiler about it: a type-3 header took the
           PACKET0 path on the hardware (boot ebfec1ec, U4 refused as P0_REG instead of P3_OP)
           while gcc-12 took the right one.  A two-bit switch leaves nothing to disagree about. */
        t = hdr >> 30;
        if (t == 1UL || t == 2UL)
            return CP_R7_WHY_TYPE;      /* type 1 carries TWO registers in the header; type 2 is ours */
        if (t == 0UL) {
            if ((hdr & 0x8000UL) != 0UL || ((hdr >> 16) & 0x3fffUL) != 0UL)
                return CP_R7_WHY_P0_COUNT;  /* one header, many registers: it would walk off the list */
            if (i + 1UL >= n)
                return CP_R7_WHY_TRUNC;
            reg = (hdr & 0x3fffUL) * 4UL;
            val = w[i + 1UL];
            if (!cpR7RegAllowed(reg))
                return CP_R7_WHY_P0_REG;
            if (!cpR7ValueAllowed(reg, val))
                return CP_R7_WHY_P0_VALUE;
            if (reg == C_SE_VTX_FMT_0) {
                fmt0 = val; sawFmt = 1;
            }
            else if (reg == C_SE_VTX_FMT_1)
                fmt1 = val;
            else if (reg == C_RB3D_COLOROFFSET)
                coff = val;
            else if (reg == C_RB3D_COLORPITCH)
                cpitch = val;
            else if (reg == C_RB3D_DEPTHOFFSET)
                zoff = val;
            else if (reg == C_RB3D_DEPTHPITCH)
                zpitch = val;
            else if (reg == C_RE_WIDTH_HEIGHT) {
                wh = val; haveWH = 1;
            } else if (reg == C_PP_TXOFFSET_0) {
                toff = val; haveT = 1;
            } else if (reg == C_PP_TXFORMAT_0) {
                tfmt = val; haveTF = 1;             /* G4-3 K3: the footprint's shape */
            } else if (reg == C_PP_TXFILTER_0)
                tfil = val;                         /* and its level count */
            i += 2UL;
            continue;
        }
        cnt = ((hdr >> 16) & 0x3fffUL) + 1UL;   /* data words after the header */
        if ((hdr & 0xff00UL) != 0x3500UL)
            return CP_R7_WHY_P3_OP;             /* 3D_DRAW_IMMD_2 is the only one we have measured */
        if (i + 1UL + cnt > n)
            return CP_R7_WHY_TRUNC;
        vf = w[i + 1UL];
        if ((vf & ~CP_R7_VF_ALLOWED) != 0UL ||
            (vf & CP_R7_VF_WALK_MASK) != CP_R7_VF_WALK_RING ||
            (vf & CP_R7_VF_PRIM_MASK) != CP_R7_VF_PRIM_TRIANGLES)
            return CP_R7_WHY_VF;                /* a non-ring walk reads the following words otherwise */
        nv = (vf >> 16) & 0xffffUL;
        if (nv == 0UL || (nv % 3UL) != 0UL)
            return CP_R7_WHY_VF;
        if (!sawFmt)
            return CP_R7_WHY_VTX_UNSET; /* the prefix defines it, but a client must still say so */
        vw = cpR7VertexWords(fmt0, fmt1);
        if (vw == 0UL)
            return CP_R7_WHY_VTX_FMT;
        if (cnt - 1UL != vw * nv)               /* cnt counts VF_CNTL as well */
            return CP_R7_WHY_COUNT;
        /* G4-4 K7: this draw reads and writes the surfaces as they are NOW */
        if (!cpR7SurfacesOk(c, coff, cpitch, zoff, zpitch, wh, haveWH, toff, tfmt, tfil, haveT, haveTF))
            return CP_R7_WHY_SURFACE;
        drew = 1;
        i += 1UL + cnt;
    }
    c->r7At = n;
    if (!drew)
        return CP_R7_WHY_EMPTY;
    if (!cpR7SurfacesOk(c, coff, cpitch, zoff, zpitch, wh, haveWH, toff, tfmt, tfil, haveT, haveTF))
        return CP_R7_WHY_SURFACE;
    return CP_R7_WHY_OK;
}

unsigned long
osrdn_r7_verify(unsigned long winStart, unsigned long winEnd, unsigned long defC,
                unsigned long defZ, unsigned long defPitch,
                const unsigned long *w, unsigned long n, unsigned long *at, unsigned long *word)
{
    osrdn_r7v v;
    unsigned long why;

    v.r7WinStart = winStart;
    v.r7WinEnd = winEnd;
    v.r7At = 0UL;
    v.r7Word = 0UL;
    why = cpR7Verify(&v, w, n, defC, defZ, defPitch);
    if (at != 0)
        *at = v.r7At;
    if (word != 0)
        *word = v.r7Word;
    return why;
}
