/*
 * OSRDNMesaVerify.h - the client-side copy of the kernel's stream verifier (G4-2 B0).
 * GENERATED by tools/mesa/gen_r7verify.py from OSRDNDisplay/OSRDNDisplay_reloc.tproj/osrdn_cp.m
 * and osrdn_cp.h -- do not edit; regenerate.  The codes are the kernel's CP_R7_WHY_*.
 */
#ifndef OSRDN_MESA_VERIFY_H
#define OSRDN_MESA_VERIFY_H

#define CP_R7_WHY_OK            0
#define CP_R7_WHY_TYPE          1
#define CP_R7_WHY_TRUNC         2
#define CP_R7_WHY_P0_COUNT      3
#define CP_R7_WHY_P0_REG        4
#define CP_R7_WHY_P0_VALUE      5
#define CP_R7_WHY_P3_OP         6
#define CP_R7_WHY_VF            7
#define CP_R7_WHY_VTX_FMT       8
#define CP_R7_WHY_VTX_UNSET     9
#define CP_R7_WHY_COUNT         10
#define CP_R7_WHY_SURFACE       11
#define CP_R7_WHY_WORDS         12
#define CP_R7_WHY_EMPTY         13
#define CP_R7_BATCH_MAX         4068

/* what the kernel's prefix leaves (osrdn_cp.h): the library passes winStart + these as defC/defZ
   and the pitch as defPitch, as the kernel's own call site does */
#define OSRDN_R7V_DEF_DEPTH_OFF     0x00000UL
#define OSRDN_R7V_DEF_COLOR_OFF     0x3c000UL
#define OSRDN_R7V_DEF_PITCH         64UL

/* the verdict on a client stream of n words for a window [winStart, winEnd) whose prefix left the
   colour surface at defC, the depth surface at defZ, both with pitch defPitch: CP_R7_WHY_OK, or the
   rule that refused, with *at the word it stopped at and *word that word */
unsigned long osrdn_r7_verify(unsigned long winStart, unsigned long winEnd, unsigned long defC,
                              unsigned long defZ, unsigned long defPitch,
                              const unsigned long *w, unsigned long n,
                              unsigned long *at, unsigned long *word);

#endif /* OSRDN_MESA_VERIFY_H */
